/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugPublicRouteImport } from './routes/debug-public'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpVerifyRouteImport } from './routes/(auth)/otp-verify'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authCompleteRegistrationRouteImport } from './routes/(auth)/complete-registration'
import { Route as authCheckEmailRouteImport } from './routes/(auth)/check-email'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDebugRouteRouteImport } from './routes/_authenticated/debug/route'
import { Route as AuthenticatedWorldsIndexRouteImport } from './routes/_authenticated/worlds/index'
import { Route as AuthenticatedUniverseIndexRouteImport } from './routes/_authenticated/universe/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedEntitiesIndexRouteImport } from './routes/_authenticated/entities/index'
import { Route as AuthenticatedDebugIndexRouteImport } from './routes/_authenticated/debug/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedWorldsWorldIdRouteImport } from './routes/_authenticated/worlds/$worldId'
import { Route as AuthenticatedTasksTimelineRouteImport } from './routes/_authenticated/tasks/timeline'
import { Route as AuthenticatedTasksKanbanRouteImport } from './routes/_authenticated/tasks/kanban'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsImportRouteImport } from './routes/_authenticated/settings/import'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedDebugVibegridLegendStateRouteImport } from './routes/_authenticated/debug/vibegrid-legend-state'
import { Route as AuthenticatedDebugUltraTableTestRouteImport } from './routes/_authenticated/debug/ultra-table-test'
import { Route as AuthenticatedDebugTestVibegridPureRouteImport } from './routes/_authenticated/debug/test-vibegrid-pure'
import { Route as AuthenticatedDebugSystemOptionsRouteImport } from './routes/_authenticated/debug/system-options'
import { Route as AuthenticatedDebugStateMachineTestRouteImport } from './routes/_authenticated/debug/state-machine-test'
import { Route as AuthenticatedDebugReactflowPositioningRouteImport } from './routes/_authenticated/debug/reactflow-positioning'
import { Route as AuthenticatedDebugLegendTableRouteImport } from './routes/_authenticated/debug/legend-table'
import { Route as AuthenticatedDebugLegendStateTestRouteImport } from './routes/_authenticated/debug/legend-state-test'
import { Route as AuthenticatedDebugEntityRoutesTestRouteImport } from './routes/_authenticated/debug/entity-routes-test'
import { Route as AuthenticatedOrgOrgIdIndexRouteImport } from './routes/_authenticated/org/$orgId/index'
import { Route as AuthenticatedSettingsAdminUsersRouteImport } from './routes/_authenticated/settings/admin.users'
import { Route as AuthenticatedOrgOrgIdTestPassiveRendererRouteImport } from './routes/_authenticated/org/$orgId/test-passive-renderer'
import { Route as AuthenticatedOrgOrgIdDashboardRouteImport } from './routes/_authenticated/org/$orgId/dashboard'
import { Route as AuthenticatedOrgOrgIdEntitiesEntityNameRouteImport } from './routes/_authenticated/org/$orgId/entities/$entityName'

const AuthenticatedDebugUltraTableLazyRouteImport = createFileRoute(
  '/_authenticated/debug/ultra-table',
)()
const AuthenticatedDebugSyncLazyRouteImport = createFileRoute(
  '/_authenticated/debug/sync',
)()
const AuthenticatedDebugMergedTableTestLazyRouteImport = createFileRoute(
  '/_authenticated/debug/merged-table-test',
)()
const AuthenticatedDebugLegendStateInvestigationLazyRouteImport =
  createFileRoute('/_authenticated/debug/legend-state-investigation')()
const AuthenticatedDebugEntityOperationsLazyRouteImport = createFileRoute(
  '/_authenticated/debug/entity-operations',
)()
const AuthenticatedDebugDatabaseLazyRouteImport = createFileRoute(
  '/_authenticated/debug/database',
)()

const DebugPublicRoute = DebugPublicRouteImport.update({
  id: '/debug-public',
  path: '/debug-public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpVerifyRoute = authOtpVerifyRouteImport.update({
  id: '/(auth)/otp-verify',
  path: '/otp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authCompleteRegistrationRoute =
  authCompleteRegistrationRouteImport.update({
    id: '/(auth)/complete-registration',
    path: '/complete-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const authCheckEmailRoute = authCheckEmailRouteImport.update({
  id: '/(auth)/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugRouteRoute = AuthenticatedDebugRouteRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorldsIndexRoute =
  AuthenticatedWorldsIndexRouteImport.update({
    id: '/worlds/',
    path: '/worlds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUniverseIndexRoute =
  AuthenticatedUniverseIndexRouteImport.update({
    id: '/universe/',
    path: '/universe/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesIndexRoute =
  AuthenticatedEntitiesIndexRouteImport.update({
    id: '/entities/',
    path: '/entities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugIndexRoute = AuthenticatedDebugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDebugRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebugUltraTableLazyRoute =
  AuthenticatedDebugUltraTableLazyRouteImport.update({
    id: '/ultra-table',
    path: '/ultra-table',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/ultra-table.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDebugSyncLazyRoute =
  AuthenticatedDebugSyncLazyRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/sync.lazy').then((d) => d.Route),
  )
const AuthenticatedDebugMergedTableTestLazyRoute =
  AuthenticatedDebugMergedTableTestLazyRouteImport.update({
    id: '/merged-table-test',
    path: '/merged-table-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/merged-table-test.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDebugLegendStateInvestigationLazyRoute =
  AuthenticatedDebugLegendStateInvestigationLazyRouteImport.update({
    id: '/legend-state-investigation',
    path: '/legend-state-investigation',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/debug/legend-state-investigation.lazy'
    ).then((d) => d.Route),
  )
const AuthenticatedDebugEntityOperationsLazyRoute =
  AuthenticatedDebugEntityOperationsLazyRouteImport.update({
    id: '/entity-operations',
    path: '/entity-operations',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/entity-operations.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDebugDatabaseLazyRoute =
  AuthenticatedDebugDatabaseLazyRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/database.lazy').then((d) => d.Route),
  )
const AuthenticatedWorldsWorldIdRoute =
  AuthenticatedWorldsWorldIdRouteImport.update({
    id: '/worlds/$worldId',
    path: '/worlds/$worldId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksTimelineRoute =
  AuthenticatedTasksTimelineRouteImport.update({
    id: '/tasks/timeline',
    path: '/tasks/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksKanbanRoute =
  AuthenticatedTasksKanbanRouteImport.update({
    id: '/tasks/kanban',
    path: '/tasks/kanban',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsImportRoute =
  AuthenticatedSettingsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedDebugVibegridLegendStateRoute =
  AuthenticatedDebugVibegridLegendStateRouteImport.update({
    id: '/vibegrid-legend-state',
    path: '/vibegrid-legend-state',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugUltraTableTestRoute =
  AuthenticatedDebugUltraTableTestRouteImport.update({
    id: '/ultra-table-test',
    path: '/ultra-table-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugTestVibegridPureRoute =
  AuthenticatedDebugTestVibegridPureRouteImport.update({
    id: '/test-vibegrid-pure',
    path: '/test-vibegrid-pure',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugSystemOptionsRoute =
  AuthenticatedDebugSystemOptionsRouteImport.update({
    id: '/system-options',
    path: '/system-options',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugStateMachineTestRoute =
  AuthenticatedDebugStateMachineTestRouteImport.update({
    id: '/state-machine-test',
    path: '/state-machine-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugReactflowPositioningRoute =
  AuthenticatedDebugReactflowPositioningRouteImport.update({
    id: '/reactflow-positioning',
    path: '/reactflow-positioning',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugLegendTableRoute =
  AuthenticatedDebugLegendTableRouteImport.update({
    id: '/legend-table',
    path: '/legend-table',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugLegendStateTestRoute =
  AuthenticatedDebugLegendStateTestRouteImport.update({
    id: '/legend-state-test',
    path: '/legend-state-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugEntityRoutesTestRoute =
  AuthenticatedDebugEntityRoutesTestRouteImport.update({
    id: '/entity-routes-test',
    path: '/entity-routes-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedOrgOrgIdIndexRoute =
  AuthenticatedOrgOrgIdIndexRouteImport.update({
    id: '/org/$orgId/',
    path: '/org/$orgId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAdminUsersRoute =
  AuthenticatedSettingsAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedOrgOrgIdTestPassiveRendererRoute =
  AuthenticatedOrgOrgIdTestPassiveRendererRouteImport.update({
    id: '/org/$orgId/test-passive-renderer',
    path: '/org/$orgId/test-passive-renderer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgOrgIdDashboardRoute =
  AuthenticatedOrgOrgIdDashboardRouteImport.update({
    id: '/org/$orgId/dashboard',
    path: '/org/$orgId/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgOrgIdEntitiesEntityNameRoute =
  AuthenticatedOrgOrgIdEntitiesEntityNameRouteImport.update({
    id: '/org/$orgId/entities/$entityName',
    path: '/org/$orgId/entities/$entityName',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/debug-public': typeof DebugPublicRoute
  '/debug': typeof AuthenticatedDebugRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/check-email': typeof authCheckEmailRoute
  '/complete-registration': typeof authCompleteRegistrationRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/otp-verify': typeof authOtpVerifyRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/debug/entity-routes-test': typeof AuthenticatedDebugEntityRoutesTestRoute
  '/debug/legend-state-test': typeof AuthenticatedDebugLegendStateTestRoute
  '/debug/legend-table': typeof AuthenticatedDebugLegendTableRoute
  '/debug/reactflow-positioning': typeof AuthenticatedDebugReactflowPositioningRoute
  '/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/debug/system-options': typeof AuthenticatedDebugSystemOptionsRoute
  '/debug/test-vibegrid-pure': typeof AuthenticatedDebugTestVibegridPureRoute
  '/debug/ultra-table-test': typeof AuthenticatedDebugUltraTableTestRoute
  '/debug/vibegrid-legend-state': typeof AuthenticatedDebugVibegridLegendStateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/import': typeof AuthenticatedSettingsImportRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/worlds/$worldId': typeof AuthenticatedWorldsWorldIdRoute
  '/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/debug/entity-operations': typeof AuthenticatedDebugEntityOperationsLazyRoute
  '/debug/legend-state-investigation': typeof AuthenticatedDebugLegendStateInvestigationLazyRoute
  '/debug/merged-table-test': typeof AuthenticatedDebugMergedTableTestLazyRoute
  '/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/debug/ultra-table': typeof AuthenticatedDebugUltraTableLazyRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/debug/': typeof AuthenticatedDebugIndexRoute
  '/entities': typeof AuthenticatedEntitiesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/universe': typeof AuthenticatedUniverseIndexRoute
  '/worlds': typeof AuthenticatedWorldsIndexRoute
  '/org/$orgId/dashboard': typeof AuthenticatedOrgOrgIdDashboardRoute
  '/org/$orgId/test-passive-renderer': typeof AuthenticatedOrgOrgIdTestPassiveRendererRoute
  '/settings/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
  '/org/$orgId': typeof AuthenticatedOrgOrgIdIndexRoute
  '/org/$orgId/entities/$entityName': typeof AuthenticatedOrgOrgIdEntitiesEntityNameRoute
}
export interface FileRoutesByTo {
  '/debug-public': typeof DebugPublicRoute
  '/check-email': typeof authCheckEmailRoute
  '/complete-registration': typeof authCompleteRegistrationRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/otp-verify': typeof authOtpVerifyRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/debug/entity-routes-test': typeof AuthenticatedDebugEntityRoutesTestRoute
  '/debug/legend-state-test': typeof AuthenticatedDebugLegendStateTestRoute
  '/debug/legend-table': typeof AuthenticatedDebugLegendTableRoute
  '/debug/reactflow-positioning': typeof AuthenticatedDebugReactflowPositioningRoute
  '/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/debug/system-options': typeof AuthenticatedDebugSystemOptionsRoute
  '/debug/test-vibegrid-pure': typeof AuthenticatedDebugTestVibegridPureRoute
  '/debug/ultra-table-test': typeof AuthenticatedDebugUltraTableTestRoute
  '/debug/vibegrid-legend-state': typeof AuthenticatedDebugVibegridLegendStateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/import': typeof AuthenticatedSettingsImportRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/worlds/$worldId': typeof AuthenticatedWorldsWorldIdRoute
  '/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/debug/entity-operations': typeof AuthenticatedDebugEntityOperationsLazyRoute
  '/debug/legend-state-investigation': typeof AuthenticatedDebugLegendStateInvestigationLazyRoute
  '/debug/merged-table-test': typeof AuthenticatedDebugMergedTableTestLazyRoute
  '/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/debug/ultra-table': typeof AuthenticatedDebugUltraTableLazyRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/debug': typeof AuthenticatedDebugIndexRoute
  '/entities': typeof AuthenticatedEntitiesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/universe': typeof AuthenticatedUniverseIndexRoute
  '/worlds': typeof AuthenticatedWorldsIndexRoute
  '/org/$orgId/dashboard': typeof AuthenticatedOrgOrgIdDashboardRoute
  '/org/$orgId/test-passive-renderer': typeof AuthenticatedOrgOrgIdTestPassiveRendererRoute
  '/settings/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
  '/org/$orgId': typeof AuthenticatedOrgOrgIdIndexRoute
  '/org/$orgId/entities/$entityName': typeof AuthenticatedOrgOrgIdEntitiesEntityNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/debug-public': typeof DebugPublicRoute
  '/_authenticated/debug': typeof AuthenticatedDebugRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/check-email': typeof authCheckEmailRoute
  '/(auth)/complete-registration': typeof authCompleteRegistrationRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/otp-verify': typeof authOtpVerifyRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/debug/entity-routes-test': typeof AuthenticatedDebugEntityRoutesTestRoute
  '/_authenticated/debug/legend-state-test': typeof AuthenticatedDebugLegendStateTestRoute
  '/_authenticated/debug/legend-table': typeof AuthenticatedDebugLegendTableRoute
  '/_authenticated/debug/reactflow-positioning': typeof AuthenticatedDebugReactflowPositioningRoute
  '/_authenticated/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/_authenticated/debug/system-options': typeof AuthenticatedDebugSystemOptionsRoute
  '/_authenticated/debug/test-vibegrid-pure': typeof AuthenticatedDebugTestVibegridPureRoute
  '/_authenticated/debug/ultra-table-test': typeof AuthenticatedDebugUltraTableTestRoute
  '/_authenticated/debug/vibegrid-legend-state': typeof AuthenticatedDebugVibegridLegendStateRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/import': typeof AuthenticatedSettingsImportRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/_authenticated/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/_authenticated/worlds/$worldId': typeof AuthenticatedWorldsWorldIdRoute
  '/_authenticated/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/_authenticated/debug/entity-operations': typeof AuthenticatedDebugEntityOperationsLazyRoute
  '/_authenticated/debug/legend-state-investigation': typeof AuthenticatedDebugLegendStateInvestigationLazyRoute
  '/_authenticated/debug/merged-table-test': typeof AuthenticatedDebugMergedTableTestLazyRoute
  '/_authenticated/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/_authenticated/debug/ultra-table': typeof AuthenticatedDebugUltraTableLazyRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/debug/': typeof AuthenticatedDebugIndexRoute
  '/_authenticated/entities/': typeof AuthenticatedEntitiesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/universe/': typeof AuthenticatedUniverseIndexRoute
  '/_authenticated/worlds/': typeof AuthenticatedWorldsIndexRoute
  '/_authenticated/org/$orgId/dashboard': typeof AuthenticatedOrgOrgIdDashboardRoute
  '/_authenticated/org/$orgId/test-passive-renderer': typeof AuthenticatedOrgOrgIdTestPassiveRendererRoute
  '/_authenticated/settings/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
  '/_authenticated/org/$orgId/': typeof AuthenticatedOrgOrgIdIndexRoute
  '/_authenticated/org/$orgId/entities/$entityName': typeof AuthenticatedOrgOrgIdEntitiesEntityNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/debug-public'
    | '/debug'
    | '/settings'
    | '/check-email'
    | '/complete-registration'
    | '/forgot-password'
    | '/otp'
    | '/otp-verify'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/debug/entity-routes-test'
    | '/debug/legend-state-test'
    | '/debug/legend-table'
    | '/debug/reactflow-positioning'
    | '/debug/state-machine-test'
    | '/debug/system-options'
    | '/debug/test-vibegrid-pure'
    | '/debug/ultra-table-test'
    | '/debug/vibegrid-legend-state'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/import'
    | '/settings/notifications'
    | '/tasks/kanban'
    | '/tasks/timeline'
    | '/worlds/$worldId'
    | '/debug/database'
    | '/debug/entity-operations'
    | '/debug/legend-state-investigation'
    | '/debug/merged-table-test'
    | '/debug/sync'
    | '/debug/ultra-table'
    | '/apps'
    | '/chats'
    | '/debug/'
    | '/entities'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/universe'
    | '/worlds'
    | '/org/$orgId/dashboard'
    | '/org/$orgId/test-passive-renderer'
    | '/settings/admin/users'
    | '/org/$orgId'
    | '/org/$orgId/entities/$entityName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/debug-public'
    | '/check-email'
    | '/complete-registration'
    | '/forgot-password'
    | '/otp'
    | '/otp-verify'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/debug/entity-routes-test'
    | '/debug/legend-state-test'
    | '/debug/legend-table'
    | '/debug/reactflow-positioning'
    | '/debug/state-machine-test'
    | '/debug/system-options'
    | '/debug/test-vibegrid-pure'
    | '/debug/ultra-table-test'
    | '/debug/vibegrid-legend-state'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/import'
    | '/settings/notifications'
    | '/tasks/kanban'
    | '/tasks/timeline'
    | '/worlds/$worldId'
    | '/debug/database'
    | '/debug/entity-operations'
    | '/debug/legend-state-investigation'
    | '/debug/merged-table-test'
    | '/debug/sync'
    | '/debug/ultra-table'
    | '/apps'
    | '/chats'
    | '/debug'
    | '/entities'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/universe'
    | '/worlds'
    | '/org/$orgId/dashboard'
    | '/org/$orgId/test-passive-renderer'
    | '/settings/admin/users'
    | '/org/$orgId'
    | '/org/$orgId/entities/$entityName'
  id:
    | '__root__'
    | '/_authenticated'
    | '/debug-public'
    | '/_authenticated/debug'
    | '/_authenticated/settings'
    | '/(auth)/check-email'
    | '/(auth)/complete-registration'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/otp-verify'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/debug/entity-routes-test'
    | '/_authenticated/debug/legend-state-test'
    | '/_authenticated/debug/legend-table'
    | '/_authenticated/debug/reactflow-positioning'
    | '/_authenticated/debug/state-machine-test'
    | '/_authenticated/debug/system-options'
    | '/_authenticated/debug/test-vibegrid-pure'
    | '/_authenticated/debug/ultra-table-test'
    | '/_authenticated/debug/vibegrid-legend-state'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/import'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/tasks/kanban'
    | '/_authenticated/tasks/timeline'
    | '/_authenticated/worlds/$worldId'
    | '/_authenticated/debug/database'
    | '/_authenticated/debug/entity-operations'
    | '/_authenticated/debug/legend-state-investigation'
    | '/_authenticated/debug/merged-table-test'
    | '/_authenticated/debug/sync'
    | '/_authenticated/debug/ultra-table'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/debug/'
    | '/_authenticated/entities/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/universe/'
    | '/_authenticated/worlds/'
    | '/_authenticated/org/$orgId/dashboard'
    | '/_authenticated/org/$orgId/test-passive-renderer'
    | '/_authenticated/settings/admin/users'
    | '/_authenticated/org/$orgId/'
    | '/_authenticated/org/$orgId/entities/$entityName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DebugPublicRoute: typeof DebugPublicRoute
  authCheckEmailRoute: typeof authCheckEmailRoute
  authCompleteRegistrationRoute: typeof authCompleteRegistrationRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authOtpVerifyRoute: typeof authOtpVerifyRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug-public': {
      id: '/debug-public'
      path: '/debug-public'
      fullPath: '/debug-public'
      preLoaderRoute: typeof DebugPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp-verify': {
      id: '/(auth)/otp-verify'
      path: '/otp-verify'
      fullPath: '/otp-verify'
      preLoaderRoute: typeof authOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/complete-registration': {
      id: '/(auth)/complete-registration'
      path: '/complete-registration'
      fullPath: '/complete-registration'
      preLoaderRoute: typeof authCompleteRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/check-email': {
      id: '/(auth)/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof authCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug': {
      id: '/_authenticated/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AuthenticatedDebugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worlds/': {
      id: '/_authenticated/worlds/'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof AuthenticatedWorldsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/universe/': {
      id: '/_authenticated/universe/'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof AuthenticatedUniverseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/': {
      id: '/_authenticated/entities/'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof AuthenticatedEntitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/': {
      id: '/_authenticated/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof AuthenticatedDebugIndexRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/ultra-table': {
      id: '/_authenticated/debug/ultra-table'
      path: '/ultra-table'
      fullPath: '/debug/ultra-table'
      preLoaderRoute: typeof AuthenticatedDebugUltraTableLazyRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/sync': {
      id: '/_authenticated/debug/sync'
      path: '/sync'
      fullPath: '/debug/sync'
      preLoaderRoute: typeof AuthenticatedDebugSyncLazyRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/merged-table-test': {
      id: '/_authenticated/debug/merged-table-test'
      path: '/merged-table-test'
      fullPath: '/debug/merged-table-test'
      preLoaderRoute: typeof AuthenticatedDebugMergedTableTestLazyRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/legend-state-investigation': {
      id: '/_authenticated/debug/legend-state-investigation'
      path: '/legend-state-investigation'
      fullPath: '/debug/legend-state-investigation'
      preLoaderRoute: typeof AuthenticatedDebugLegendStateInvestigationLazyRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/entity-operations': {
      id: '/_authenticated/debug/entity-operations'
      path: '/entity-operations'
      fullPath: '/debug/entity-operations'
      preLoaderRoute: typeof AuthenticatedDebugEntityOperationsLazyRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/database': {
      id: '/_authenticated/debug/database'
      path: '/database'
      fullPath: '/debug/database'
      preLoaderRoute: typeof AuthenticatedDebugDatabaseLazyRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/worlds/$worldId': {
      id: '/_authenticated/worlds/$worldId'
      path: '/worlds/$worldId'
      fullPath: '/worlds/$worldId'
      preLoaderRoute: typeof AuthenticatedWorldsWorldIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/timeline': {
      id: '/_authenticated/tasks/timeline'
      path: '/tasks/timeline'
      fullPath: '/tasks/timeline'
      preLoaderRoute: typeof AuthenticatedTasksTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/kanban': {
      id: '/_authenticated/tasks/kanban'
      path: '/tasks/kanban'
      fullPath: '/tasks/kanban'
      preLoaderRoute: typeof AuthenticatedTasksKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/import': {
      id: '/_authenticated/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AuthenticatedSettingsImportRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/debug/vibegrid-legend-state': {
      id: '/_authenticated/debug/vibegrid-legend-state'
      path: '/vibegrid-legend-state'
      fullPath: '/debug/vibegrid-legend-state'
      preLoaderRoute: typeof AuthenticatedDebugVibegridLegendStateRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/ultra-table-test': {
      id: '/_authenticated/debug/ultra-table-test'
      path: '/ultra-table-test'
      fullPath: '/debug/ultra-table-test'
      preLoaderRoute: typeof AuthenticatedDebugUltraTableTestRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/test-vibegrid-pure': {
      id: '/_authenticated/debug/test-vibegrid-pure'
      path: '/test-vibegrid-pure'
      fullPath: '/debug/test-vibegrid-pure'
      preLoaderRoute: typeof AuthenticatedDebugTestVibegridPureRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/system-options': {
      id: '/_authenticated/debug/system-options'
      path: '/system-options'
      fullPath: '/debug/system-options'
      preLoaderRoute: typeof AuthenticatedDebugSystemOptionsRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/state-machine-test': {
      id: '/_authenticated/debug/state-machine-test'
      path: '/state-machine-test'
      fullPath: '/debug/state-machine-test'
      preLoaderRoute: typeof AuthenticatedDebugStateMachineTestRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/reactflow-positioning': {
      id: '/_authenticated/debug/reactflow-positioning'
      path: '/reactflow-positioning'
      fullPath: '/debug/reactflow-positioning'
      preLoaderRoute: typeof AuthenticatedDebugReactflowPositioningRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/legend-table': {
      id: '/_authenticated/debug/legend-table'
      path: '/legend-table'
      fullPath: '/debug/legend-table'
      preLoaderRoute: typeof AuthenticatedDebugLegendTableRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/legend-state-test': {
      id: '/_authenticated/debug/legend-state-test'
      path: '/legend-state-test'
      fullPath: '/debug/legend-state-test'
      preLoaderRoute: typeof AuthenticatedDebugLegendStateTestRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/entity-routes-test': {
      id: '/_authenticated/debug/entity-routes-test'
      path: '/entity-routes-test'
      fullPath: '/debug/entity-routes-test'
      preLoaderRoute: typeof AuthenticatedDebugEntityRoutesTestRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/org/$orgId/': {
      id: '/_authenticated/org/$orgId/'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof AuthenticatedOrgOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/admin/users': {
      id: '/_authenticated/settings/admin/users'
      path: '/admin/users'
      fullPath: '/settings/admin/users'
      preLoaderRoute: typeof AuthenticatedSettingsAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/org/$orgId/test-passive-renderer': {
      id: '/_authenticated/org/$orgId/test-passive-renderer'
      path: '/org/$orgId/test-passive-renderer'
      fullPath: '/org/$orgId/test-passive-renderer'
      preLoaderRoute: typeof AuthenticatedOrgOrgIdTestPassiveRendererRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/$orgId/dashboard': {
      id: '/_authenticated/org/$orgId/dashboard'
      path: '/org/$orgId/dashboard'
      fullPath: '/org/$orgId/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgOrgIdDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/$orgId/entities/$entityName': {
      id: '/_authenticated/org/$orgId/entities/$entityName'
      path: '/org/$orgId/entities/$entityName'
      fullPath: '/org/$orgId/entities/$entityName'
      preLoaderRoute: typeof AuthenticatedOrgOrgIdEntitiesEntityNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDebugRouteRouteChildren {
  AuthenticatedDebugEntityRoutesTestRoute: typeof AuthenticatedDebugEntityRoutesTestRoute
  AuthenticatedDebugLegendStateTestRoute: typeof AuthenticatedDebugLegendStateTestRoute
  AuthenticatedDebugLegendTableRoute: typeof AuthenticatedDebugLegendTableRoute
  AuthenticatedDebugReactflowPositioningRoute: typeof AuthenticatedDebugReactflowPositioningRoute
  AuthenticatedDebugStateMachineTestRoute: typeof AuthenticatedDebugStateMachineTestRoute
  AuthenticatedDebugSystemOptionsRoute: typeof AuthenticatedDebugSystemOptionsRoute
  AuthenticatedDebugTestVibegridPureRoute: typeof AuthenticatedDebugTestVibegridPureRoute
  AuthenticatedDebugUltraTableTestRoute: typeof AuthenticatedDebugUltraTableTestRoute
  AuthenticatedDebugVibegridLegendStateRoute: typeof AuthenticatedDebugVibegridLegendStateRoute
  AuthenticatedDebugDatabaseLazyRoute: typeof AuthenticatedDebugDatabaseLazyRoute
  AuthenticatedDebugEntityOperationsLazyRoute: typeof AuthenticatedDebugEntityOperationsLazyRoute
  AuthenticatedDebugLegendStateInvestigationLazyRoute: typeof AuthenticatedDebugLegendStateInvestigationLazyRoute
  AuthenticatedDebugMergedTableTestLazyRoute: typeof AuthenticatedDebugMergedTableTestLazyRoute
  AuthenticatedDebugSyncLazyRoute: typeof AuthenticatedDebugSyncLazyRoute
  AuthenticatedDebugUltraTableLazyRoute: typeof AuthenticatedDebugUltraTableLazyRoute
  AuthenticatedDebugIndexRoute: typeof AuthenticatedDebugIndexRoute
}

const AuthenticatedDebugRouteRouteChildren: AuthenticatedDebugRouteRouteChildren =
  {
    AuthenticatedDebugEntityRoutesTestRoute:
      AuthenticatedDebugEntityRoutesTestRoute,
    AuthenticatedDebugLegendStateTestRoute:
      AuthenticatedDebugLegendStateTestRoute,
    AuthenticatedDebugLegendTableRoute: AuthenticatedDebugLegendTableRoute,
    AuthenticatedDebugReactflowPositioningRoute:
      AuthenticatedDebugReactflowPositioningRoute,
    AuthenticatedDebugStateMachineTestRoute:
      AuthenticatedDebugStateMachineTestRoute,
    AuthenticatedDebugSystemOptionsRoute: AuthenticatedDebugSystemOptionsRoute,
    AuthenticatedDebugTestVibegridPureRoute:
      AuthenticatedDebugTestVibegridPureRoute,
    AuthenticatedDebugUltraTableTestRoute:
      AuthenticatedDebugUltraTableTestRoute,
    AuthenticatedDebugVibegridLegendStateRoute:
      AuthenticatedDebugVibegridLegendStateRoute,
    AuthenticatedDebugDatabaseLazyRoute: AuthenticatedDebugDatabaseLazyRoute,
    AuthenticatedDebugEntityOperationsLazyRoute:
      AuthenticatedDebugEntityOperationsLazyRoute,
    AuthenticatedDebugLegendStateInvestigationLazyRoute:
      AuthenticatedDebugLegendStateInvestigationLazyRoute,
    AuthenticatedDebugMergedTableTestLazyRoute:
      AuthenticatedDebugMergedTableTestLazyRoute,
    AuthenticatedDebugSyncLazyRoute: AuthenticatedDebugSyncLazyRoute,
    AuthenticatedDebugUltraTableLazyRoute:
      AuthenticatedDebugUltraTableLazyRoute,
    AuthenticatedDebugIndexRoute: AuthenticatedDebugIndexRoute,
  }

const AuthenticatedDebugRouteRouteWithChildren =
  AuthenticatedDebugRouteRoute._addFileChildren(
    AuthenticatedDebugRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsImportRoute: typeof AuthenticatedSettingsImportRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsAdminUsersRoute: typeof AuthenticatedSettingsAdminUsersRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsImportRoute: AuthenticatedSettingsImportRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsAdminUsersRoute: AuthenticatedSettingsAdminUsersRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDebugRouteRoute: typeof AuthenticatedDebugRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTasksKanbanRoute: typeof AuthenticatedTasksKanbanRoute
  AuthenticatedTasksTimelineRoute: typeof AuthenticatedTasksTimelineRoute
  AuthenticatedWorldsWorldIdRoute: typeof AuthenticatedWorldsWorldIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedEntitiesIndexRoute: typeof AuthenticatedEntitiesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUniverseIndexRoute: typeof AuthenticatedUniverseIndexRoute
  AuthenticatedWorldsIndexRoute: typeof AuthenticatedWorldsIndexRoute
  AuthenticatedOrgOrgIdDashboardRoute: typeof AuthenticatedOrgOrgIdDashboardRoute
  AuthenticatedOrgOrgIdTestPassiveRendererRoute: typeof AuthenticatedOrgOrgIdTestPassiveRendererRoute
  AuthenticatedOrgOrgIdIndexRoute: typeof AuthenticatedOrgOrgIdIndexRoute
  AuthenticatedOrgOrgIdEntitiesEntityNameRoute: typeof AuthenticatedOrgOrgIdEntitiesEntityNameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDebugRouteRoute: AuthenticatedDebugRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTasksKanbanRoute: AuthenticatedTasksKanbanRoute,
  AuthenticatedTasksTimelineRoute: AuthenticatedTasksTimelineRoute,
  AuthenticatedWorldsWorldIdRoute: AuthenticatedWorldsWorldIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedEntitiesIndexRoute: AuthenticatedEntitiesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUniverseIndexRoute: AuthenticatedUniverseIndexRoute,
  AuthenticatedWorldsIndexRoute: AuthenticatedWorldsIndexRoute,
  AuthenticatedOrgOrgIdDashboardRoute: AuthenticatedOrgOrgIdDashboardRoute,
  AuthenticatedOrgOrgIdTestPassiveRendererRoute:
    AuthenticatedOrgOrgIdTestPassiveRendererRoute,
  AuthenticatedOrgOrgIdIndexRoute: AuthenticatedOrgOrgIdIndexRoute,
  AuthenticatedOrgOrgIdEntitiesEntityNameRoute:
    AuthenticatedOrgOrgIdEntitiesEntityNameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DebugPublicRoute: DebugPublicRoute,
  authCheckEmailRoute: authCheckEmailRoute,
  authCompleteRegistrationRoute: authCompleteRegistrationRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authOtpVerifyRoute: authOtpVerifyRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
