/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2Import } from './routes/(auth)/sign-in-2'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDebugRouteImport } from './routes/_authenticated/debug/route'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProjectsIndexImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedHelpCenterIndexImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDebugIndexImport } from './routes/_authenticated/debug/index'
import { Route as AuthenticatedChatsIndexImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProjectsProjectIdImport } from './routes/_authenticated/projects/$projectId'

// Create Virtual Routes

const AuthenticatedDebugTypeormTestLazyImport = createFileRoute(
  '/_authenticated/debug/typeorm-test',
)()
const AuthenticatedDebugTasksNewPatternLazyImport = createFileRoute(
  '/_authenticated/debug/tasks-new-pattern',
)()
const AuthenticatedDebugSyncTestLazyImport = createFileRoute(
  '/_authenticated/debug/sync-test',
)()
const AuthenticatedDebugSyncChangesLazyImport = createFileRoute(
  '/_authenticated/debug/sync-changes',
)()
const AuthenticatedDebugSyncLazyImport = createFileRoute(
  '/_authenticated/debug/sync',
)()
const AuthenticatedDebugPerformanceLazyImport = createFileRoute(
  '/_authenticated/debug/performance',
)()
const AuthenticatedDebugMultiQueryLazyImport = createFileRoute(
  '/_authenticated/debug/multi-query',
)()
const AuthenticatedDebugLiveQueryLazyImport = createFileRoute(
  '/_authenticated/debug/live-query',
)()
const AuthenticatedDebugIntegrityLazyImport = createFileRoute(
  '/_authenticated/debug/integrity',
)()
const AuthenticatedDebugDatabaseLazyImport = createFileRoute(
  '/_authenticated/debug/database',
)()
const AuthenticatedDebugDataTableAtomLazyImport = createFileRoute(
  '/_authenticated/debug/data-table-atom',
)()
const AuthenticatedDebugDataTableLazyImport = createFileRoute(
  '/_authenticated/debug/data-table',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignIn2Route = authSignIn2Import.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedDebugRouteRoute = AuthenticatedDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedProjectsIndexRoute = AuthenticatedProjectsIndexImport.update(
  {
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedDebugIndexRoute = AuthenticatedDebugIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDebugRouteRoute,
} as any)

const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDebugTypeormTestLazyRoute =
  AuthenticatedDebugTypeormTestLazyImport.update({
    id: '/typeorm-test',
    path: '/typeorm-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/typeorm-test.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDebugTasksNewPatternLazyRoute =
  AuthenticatedDebugTasksNewPatternLazyImport.update({
    id: '/tasks-new-pattern',
    path: '/tasks-new-pattern',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/tasks-new-pattern.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDebugSyncTestLazyRoute =
  AuthenticatedDebugSyncTestLazyImport.update({
    id: '/sync-test',
    path: '/sync-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/sync-test.lazy').then((d) => d.Route),
  )

const AuthenticatedDebugSyncChangesLazyRoute =
  AuthenticatedDebugSyncChangesLazyImport.update({
    id: '/sync-changes',
    path: '/sync-changes',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/sync-changes.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDebugSyncLazyRoute = AuthenticatedDebugSyncLazyImport.update(
  {
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/debug/sync.lazy').then((d) => d.Route),
)

const AuthenticatedDebugPerformanceLazyRoute =
  AuthenticatedDebugPerformanceLazyImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/performance.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDebugMultiQueryLazyRoute =
  AuthenticatedDebugMultiQueryLazyImport.update({
    id: '/multi-query',
    path: '/multi-query',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/multi-query.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDebugLiveQueryLazyRoute =
  AuthenticatedDebugLiveQueryLazyImport.update({
    id: '/live-query',
    path: '/live-query',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/live-query.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDebugIntegrityLazyRoute =
  AuthenticatedDebugIntegrityLazyImport.update({
    id: '/integrity',
    path: '/integrity',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/integrity.lazy').then((d) => d.Route),
  )

const AuthenticatedDebugDatabaseLazyRoute =
  AuthenticatedDebugDatabaseLazyImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/database.lazy').then((d) => d.Route),
  )

const AuthenticatedDebugDataTableAtomLazyRoute =
  AuthenticatedDebugDataTableAtomLazyImport.update({
    id: '/data-table-atom',
    path: '/data-table-atom',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/data-table-atom.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDebugDataTableLazyRoute =
  AuthenticatedDebugDataTableLazyImport.update({
    id: '/data-table',
    path: '/data-table',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/data-table.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/debug': {
      id: '/_authenticated/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AuthenticatedDebugRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/debug/data-table': {
      id: '/_authenticated/debug/data-table'
      path: '/data-table'
      fullPath: '/debug/data-table'
      preLoaderRoute: typeof AuthenticatedDebugDataTableLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/data-table-atom': {
      id: '/_authenticated/debug/data-table-atom'
      path: '/data-table-atom'
      fullPath: '/debug/data-table-atom'
      preLoaderRoute: typeof AuthenticatedDebugDataTableAtomLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/database': {
      id: '/_authenticated/debug/database'
      path: '/database'
      fullPath: '/debug/database'
      preLoaderRoute: typeof AuthenticatedDebugDatabaseLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/integrity': {
      id: '/_authenticated/debug/integrity'
      path: '/integrity'
      fullPath: '/debug/integrity'
      preLoaderRoute: typeof AuthenticatedDebugIntegrityLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/live-query': {
      id: '/_authenticated/debug/live-query'
      path: '/live-query'
      fullPath: '/debug/live-query'
      preLoaderRoute: typeof AuthenticatedDebugLiveQueryLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/multi-query': {
      id: '/_authenticated/debug/multi-query'
      path: '/multi-query'
      fullPath: '/debug/multi-query'
      preLoaderRoute: typeof AuthenticatedDebugMultiQueryLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/performance': {
      id: '/_authenticated/debug/performance'
      path: '/performance'
      fullPath: '/debug/performance'
      preLoaderRoute: typeof AuthenticatedDebugPerformanceLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/sync': {
      id: '/_authenticated/debug/sync'
      path: '/sync'
      fullPath: '/debug/sync'
      preLoaderRoute: typeof AuthenticatedDebugSyncLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/sync-changes': {
      id: '/_authenticated/debug/sync-changes'
      path: '/sync-changes'
      fullPath: '/debug/sync-changes'
      preLoaderRoute: typeof AuthenticatedDebugSyncChangesLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/sync-test': {
      id: '/_authenticated/debug/sync-test'
      path: '/sync-test'
      fullPath: '/debug/sync-test'
      preLoaderRoute: typeof AuthenticatedDebugSyncTestLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/tasks-new-pattern': {
      id: '/_authenticated/debug/tasks-new-pattern'
      path: '/tasks-new-pattern'
      fullPath: '/debug/tasks-new-pattern'
      preLoaderRoute: typeof AuthenticatedDebugTasksNewPatternLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/typeorm-test': {
      id: '/_authenticated/debug/typeorm-test'
      path: '/typeorm-test'
      fullPath: '/debug/typeorm-test'
      preLoaderRoute: typeof AuthenticatedDebugTypeormTestLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/debug/': {
      id: '/_authenticated/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof AuthenticatedDebugIndexImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDebugRouteRouteChildren {
  AuthenticatedDebugDataTableLazyRoute: typeof AuthenticatedDebugDataTableLazyRoute
  AuthenticatedDebugDataTableAtomLazyRoute: typeof AuthenticatedDebugDataTableAtomLazyRoute
  AuthenticatedDebugDatabaseLazyRoute: typeof AuthenticatedDebugDatabaseLazyRoute
  AuthenticatedDebugIntegrityLazyRoute: typeof AuthenticatedDebugIntegrityLazyRoute
  AuthenticatedDebugLiveQueryLazyRoute: typeof AuthenticatedDebugLiveQueryLazyRoute
  AuthenticatedDebugMultiQueryLazyRoute: typeof AuthenticatedDebugMultiQueryLazyRoute
  AuthenticatedDebugPerformanceLazyRoute: typeof AuthenticatedDebugPerformanceLazyRoute
  AuthenticatedDebugSyncLazyRoute: typeof AuthenticatedDebugSyncLazyRoute
  AuthenticatedDebugSyncChangesLazyRoute: typeof AuthenticatedDebugSyncChangesLazyRoute
  AuthenticatedDebugSyncTestLazyRoute: typeof AuthenticatedDebugSyncTestLazyRoute
  AuthenticatedDebugTasksNewPatternLazyRoute: typeof AuthenticatedDebugTasksNewPatternLazyRoute
  AuthenticatedDebugTypeormTestLazyRoute: typeof AuthenticatedDebugTypeormTestLazyRoute
  AuthenticatedDebugIndexRoute: typeof AuthenticatedDebugIndexRoute
}

const AuthenticatedDebugRouteRouteChildren: AuthenticatedDebugRouteRouteChildren =
  {
    AuthenticatedDebugDataTableLazyRoute: AuthenticatedDebugDataTableLazyRoute,
    AuthenticatedDebugDataTableAtomLazyRoute:
      AuthenticatedDebugDataTableAtomLazyRoute,
    AuthenticatedDebugDatabaseLazyRoute: AuthenticatedDebugDatabaseLazyRoute,
    AuthenticatedDebugIntegrityLazyRoute: AuthenticatedDebugIntegrityLazyRoute,
    AuthenticatedDebugLiveQueryLazyRoute: AuthenticatedDebugLiveQueryLazyRoute,
    AuthenticatedDebugMultiQueryLazyRoute:
      AuthenticatedDebugMultiQueryLazyRoute,
    AuthenticatedDebugPerformanceLazyRoute:
      AuthenticatedDebugPerformanceLazyRoute,
    AuthenticatedDebugSyncLazyRoute: AuthenticatedDebugSyncLazyRoute,
    AuthenticatedDebugSyncChangesLazyRoute:
      AuthenticatedDebugSyncChangesLazyRoute,
    AuthenticatedDebugSyncTestLazyRoute: AuthenticatedDebugSyncTestLazyRoute,
    AuthenticatedDebugTasksNewPatternLazyRoute:
      AuthenticatedDebugTasksNewPatternLazyRoute,
    AuthenticatedDebugTypeormTestLazyRoute:
      AuthenticatedDebugTypeormTestLazyRoute,
    AuthenticatedDebugIndexRoute: AuthenticatedDebugIndexRoute,
  }

const AuthenticatedDebugRouteRouteWithChildren =
  AuthenticatedDebugRouteRoute._addFileChildren(
    AuthenticatedDebugRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDebugRouteRoute: typeof AuthenticatedDebugRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDebugRouteRoute: AuthenticatedDebugRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/debug': typeof AuthenticatedDebugRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/debug/data-table': typeof AuthenticatedDebugDataTableLazyRoute
  '/debug/data-table-atom': typeof AuthenticatedDebugDataTableAtomLazyRoute
  '/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/debug/integrity': typeof AuthenticatedDebugIntegrityLazyRoute
  '/debug/live-query': typeof AuthenticatedDebugLiveQueryLazyRoute
  '/debug/multi-query': typeof AuthenticatedDebugMultiQueryLazyRoute
  '/debug/performance': typeof AuthenticatedDebugPerformanceLazyRoute
  '/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/debug/sync-changes': typeof AuthenticatedDebugSyncChangesLazyRoute
  '/debug/sync-test': typeof AuthenticatedDebugSyncTestLazyRoute
  '/debug/tasks-new-pattern': typeof AuthenticatedDebugTasksNewPatternLazyRoute
  '/debug/typeorm-test': typeof AuthenticatedDebugTypeormTestLazyRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/debug/': typeof AuthenticatedDebugIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}

export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/debug/data-table': typeof AuthenticatedDebugDataTableLazyRoute
  '/debug/data-table-atom': typeof AuthenticatedDebugDataTableAtomLazyRoute
  '/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/debug/integrity': typeof AuthenticatedDebugIntegrityLazyRoute
  '/debug/live-query': typeof AuthenticatedDebugLiveQueryLazyRoute
  '/debug/multi-query': typeof AuthenticatedDebugMultiQueryLazyRoute
  '/debug/performance': typeof AuthenticatedDebugPerformanceLazyRoute
  '/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/debug/sync-changes': typeof AuthenticatedDebugSyncChangesLazyRoute
  '/debug/sync-test': typeof AuthenticatedDebugSyncTestLazyRoute
  '/debug/tasks-new-pattern': typeof AuthenticatedDebugTasksNewPatternLazyRoute
  '/debug/typeorm-test': typeof AuthenticatedDebugTypeormTestLazyRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/debug': typeof AuthenticatedDebugIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/debug': typeof AuthenticatedDebugRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/debug/data-table': typeof AuthenticatedDebugDataTableLazyRoute
  '/_authenticated/debug/data-table-atom': typeof AuthenticatedDebugDataTableAtomLazyRoute
  '/_authenticated/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/_authenticated/debug/integrity': typeof AuthenticatedDebugIntegrityLazyRoute
  '/_authenticated/debug/live-query': typeof AuthenticatedDebugLiveQueryLazyRoute
  '/_authenticated/debug/multi-query': typeof AuthenticatedDebugMultiQueryLazyRoute
  '/_authenticated/debug/performance': typeof AuthenticatedDebugPerformanceLazyRoute
  '/_authenticated/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/_authenticated/debug/sync-changes': typeof AuthenticatedDebugSyncChangesLazyRoute
  '/_authenticated/debug/sync-test': typeof AuthenticatedDebugSyncTestLazyRoute
  '/_authenticated/debug/tasks-new-pattern': typeof AuthenticatedDebugTasksNewPatternLazyRoute
  '/_authenticated/debug/typeorm-test': typeof AuthenticatedDebugTypeormTestLazyRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/debug/': typeof AuthenticatedDebugIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/debug'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/debug/data-table'
    | '/debug/data-table-atom'
    | '/debug/database'
    | '/debug/integrity'
    | '/debug/live-query'
    | '/debug/multi-query'
    | '/debug/performance'
    | '/debug/sync'
    | '/debug/sync-changes'
    | '/debug/sync-test'
    | '/debug/tasks-new-pattern'
    | '/debug/typeorm-test'
    | '/apps'
    | '/chats'
    | '/debug/'
    | '/help-center'
    | '/projects'
    | '/settings/'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/debug/data-table'
    | '/debug/data-table-atom'
    | '/debug/database'
    | '/debug/integrity'
    | '/debug/live-query'
    | '/debug/multi-query'
    | '/debug/performance'
    | '/debug/sync'
    | '/debug/sync-changes'
    | '/debug/sync-test'
    | '/debug/tasks-new-pattern'
    | '/debug/typeorm-test'
    | '/apps'
    | '/chats'
    | '/debug'
    | '/help-center'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/debug'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/debug/data-table'
    | '/_authenticated/debug/data-table-atom'
    | '/_authenticated/debug/database'
    | '/_authenticated/debug/integrity'
    | '/_authenticated/debug/live-query'
    | '/_authenticated/debug/multi-query'
    | '/_authenticated/debug/performance'
    | '/_authenticated/debug/sync'
    | '/_authenticated/debug/sync-changes'
    | '/_authenticated/debug/sync-test'
    | '/_authenticated/debug/tasks-new-pattern'
    | '/_authenticated/debug/typeorm-test'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/debug/'
    | '/_authenticated/help-center/'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/forgot-password",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/debug",
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/projects/$projectId",
        "/_authenticated/apps/",
        "/_authenticated/chats/",
        "/_authenticated/help-center/",
        "/_authenticated/projects/",
        "/_authenticated/tasks/",
        "/_authenticated/users/"
      ]
    },
    "/_authenticated/debug": {
      "filePath": "_authenticated/debug/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/debug/data-table",
        "/_authenticated/debug/data-table-atom",
        "/_authenticated/debug/database",
        "/_authenticated/debug/integrity",
        "/_authenticated/debug/live-query",
        "/_authenticated/debug/multi-query",
        "/_authenticated/debug/performance",
        "/_authenticated/debug/sync",
        "/_authenticated/debug/sync-changes",
        "/_authenticated/debug/sync-test",
        "/_authenticated/debug/tasks-new-pattern",
        "/_authenticated/debug/typeorm-test",
        "/_authenticated/debug/"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/$projectId": {
      "filePath": "_authenticated/projects/$projectId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/debug/data-table": {
      "filePath": "_authenticated/debug/data-table.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/data-table-atom": {
      "filePath": "_authenticated/debug/data-table-atom.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/database": {
      "filePath": "_authenticated/debug/database.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/integrity": {
      "filePath": "_authenticated/debug/integrity.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/live-query": {
      "filePath": "_authenticated/debug/live-query.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/multi-query": {
      "filePath": "_authenticated/debug/multi-query.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/performance": {
      "filePath": "_authenticated/debug/performance.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/sync": {
      "filePath": "_authenticated/debug/sync.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/sync-changes": {
      "filePath": "_authenticated/debug/sync-changes.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/sync-test": {
      "filePath": "_authenticated/debug/sync-test.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/tasks-new-pattern": {
      "filePath": "_authenticated/debug/tasks-new-pattern.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/typeorm-test": {
      "filePath": "_authenticated/debug/typeorm-test.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/debug/": {
      "filePath": "_authenticated/debug/index.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/": {
      "filePath": "_authenticated/projects/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
