/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authVerifyEmailImport } from './routes/(auth)/verify-email'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2Import } from './routes/(auth)/sign-in-2'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpVerifyImport } from './routes/(auth)/otp-verify'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as authCompleteRegistrationImport } from './routes/(auth)/complete-registration'
import { Route as authCheckEmailImport } from './routes/(auth)/check-email'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDebugRouteImport } from './routes/_authenticated/debug/route'
import { Route as AuthenticatedTasksIndexImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProjectsIndexImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedHelpCenterIndexImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDebugIndexImport } from './routes/_authenticated/debug/index'
import { Route as AuthenticatedChatsIndexImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedTasksTimelineImport } from './routes/_authenticated/tasks/timeline'
import { Route as AuthenticatedTasksKanbanImport } from './routes/_authenticated/tasks/kanban'
import { Route as AuthenticatedSettingsNotificationsImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProjectsProjectIdImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedDebugVibegriddexTestImport } from './routes/_authenticated/debug/vibegriddex-test'
import { Route as AuthenticatedDebugVibeganttImport } from './routes/_authenticated/debug/vibegantt'
import { Route as AuthenticatedDebugStateMachineTestImport } from './routes/_authenticated/debug/state-machine-test'
import { Route as AuthenticatedDebugReactflowPositioningImport } from './routes/_authenticated/debug/reactflow-positioning'
import { Route as AuthenticatedDebugKanbanImport } from './routes/_authenticated/debug/kanban'
import { Route as authResetPasswordTokenImport } from './routes/(auth)/reset-password.$token'
import { Route as AuthenticatedSettingsAdminUsersImport } from './routes/_authenticated/settings/admin.users'

// Create Virtual Routes

const AuthenticatedDebugSyncTestLazyImport = createFileRoute(
  '/_authenticated/debug/sync-test',
)()
const AuthenticatedDebugSyncLazyImport = createFileRoute(
  '/_authenticated/debug/sync',
)()
const AuthenticatedDebugIntegrityLazyImport = createFileRoute(
  '/_authenticated/debug/integrity',
)()
const AuthenticatedDebugDatabaseLazyImport = createFileRoute(
  '/_authenticated/debug/database',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authVerifyEmailRoute = authVerifyEmailImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignIn2Route = authSignIn2Import.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpVerifyRoute = authOtpVerifyImport.update({
  id: '/(auth)/otp-verify',
  path: '/otp-verify',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const authCompleteRegistrationRoute = authCompleteRegistrationImport.update({
  id: '/(auth)/complete-registration',
  path: '/complete-registration',
  getParentRoute: () => rootRoute,
} as any)

const authCheckEmailRoute = authCheckEmailImport.update({
  id: '/(auth)/check-email',
  path: '/check-email',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedDebugRouteRoute = AuthenticatedDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedProjectsIndexRoute = AuthenticatedProjectsIndexImport.update(
  {
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedDebugIndexRoute = AuthenticatedDebugIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDebugRouteRoute,
} as any)

const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDebugSyncTestLazyRoute =
  AuthenticatedDebugSyncTestLazyImport.update({
    id: '/sync-test',
    path: '/sync-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/sync-test.lazy').then((d) => d.Route),
  )

const AuthenticatedDebugSyncLazyRoute = AuthenticatedDebugSyncLazyImport.update(
  {
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/debug/sync.lazy').then((d) => d.Route),
)

const AuthenticatedDebugIntegrityLazyRoute =
  AuthenticatedDebugIntegrityLazyImport.update({
    id: '/integrity',
    path: '/integrity',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/integrity.lazy').then((d) => d.Route),
  )

const AuthenticatedDebugDatabaseLazyRoute =
  AuthenticatedDebugDatabaseLazyImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/database.lazy').then((d) => d.Route),
  )

const AuthenticatedTasksTimelineRoute = AuthenticatedTasksTimelineImport.update(
  {
    id: '/tasks/timeline',
    path: '/tasks/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedTasksKanbanRoute = AuthenticatedTasksKanbanImport.update({
  id: '/tasks/kanban',
  path: '/tasks/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedDebugVibegriddexTestRoute =
  AuthenticatedDebugVibegriddexTestImport.update({
    id: '/vibegriddex-test',
    path: '/vibegriddex-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)

const AuthenticatedDebugVibeganttRoute =
  AuthenticatedDebugVibeganttImport.update({
    id: '/vibegantt',
    path: '/vibegantt',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)

const AuthenticatedDebugStateMachineTestRoute =
  AuthenticatedDebugStateMachineTestImport.update({
    id: '/state-machine-test',
    path: '/state-machine-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)

const AuthenticatedDebugReactflowPositioningRoute =
  AuthenticatedDebugReactflowPositioningImport.update({
    id: '/reactflow-positioning',
    path: '/reactflow-positioning',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)

const AuthenticatedDebugKanbanRoute = AuthenticatedDebugKanbanImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedDebugRouteRoute,
} as any)

const authResetPasswordTokenRoute = authResetPasswordTokenImport.update({
  id: '/(auth)/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsAdminUsersRoute =
  AuthenticatedSettingsAdminUsersImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/debug': {
      id: '/_authenticated/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AuthenticatedDebugRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/check-email': {
      id: '/(auth)/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof authCheckEmailImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/complete-registration': {
      id: '/(auth)/complete-registration'
      path: '/complete-registration'
      fullPath: '/complete-registration'
      preLoaderRoute: typeof authCompleteRegistrationImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp-verify': {
      id: '/(auth)/otp-verify'
      path: '/otp-verify'
      fullPath: '/otp-verify'
      preLoaderRoute: typeof authOtpVerifyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/reset-password/$token': {
      id: '/(auth)/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof authResetPasswordTokenImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/debug/kanban': {
      id: '/_authenticated/debug/kanban'
      path: '/kanban'
      fullPath: '/debug/kanban'
      preLoaderRoute: typeof AuthenticatedDebugKanbanImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/reactflow-positioning': {
      id: '/_authenticated/debug/reactflow-positioning'
      path: '/reactflow-positioning'
      fullPath: '/debug/reactflow-positioning'
      preLoaderRoute: typeof AuthenticatedDebugReactflowPositioningImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/state-machine-test': {
      id: '/_authenticated/debug/state-machine-test'
      path: '/state-machine-test'
      fullPath: '/debug/state-machine-test'
      preLoaderRoute: typeof AuthenticatedDebugStateMachineTestImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/vibegantt': {
      id: '/_authenticated/debug/vibegantt'
      path: '/vibegantt'
      fullPath: '/debug/vibegantt'
      preLoaderRoute: typeof AuthenticatedDebugVibeganttImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/vibegriddex-test': {
      id: '/_authenticated/debug/vibegriddex-test'
      path: '/vibegriddex-test'
      fullPath: '/debug/vibegriddex-test'
      preLoaderRoute: typeof AuthenticatedDebugVibegriddexTestImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/tasks/kanban': {
      id: '/_authenticated/tasks/kanban'
      path: '/tasks/kanban'
      fullPath: '/tasks/kanban'
      preLoaderRoute: typeof AuthenticatedTasksKanbanImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tasks/timeline': {
      id: '/_authenticated/tasks/timeline'
      path: '/tasks/timeline'
      fullPath: '/tasks/timeline'
      preLoaderRoute: typeof AuthenticatedTasksTimelineImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/debug/database': {
      id: '/_authenticated/debug/database'
      path: '/database'
      fullPath: '/debug/database'
      preLoaderRoute: typeof AuthenticatedDebugDatabaseLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/integrity': {
      id: '/_authenticated/debug/integrity'
      path: '/integrity'
      fullPath: '/debug/integrity'
      preLoaderRoute: typeof AuthenticatedDebugIntegrityLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/sync': {
      id: '/_authenticated/debug/sync'
      path: '/sync'
      fullPath: '/debug/sync'
      preLoaderRoute: typeof AuthenticatedDebugSyncLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/debug/sync-test': {
      id: '/_authenticated/debug/sync-test'
      path: '/sync-test'
      fullPath: '/debug/sync-test'
      preLoaderRoute: typeof AuthenticatedDebugSyncTestLazyImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/debug/': {
      id: '/_authenticated/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof AuthenticatedDebugIndexImport
      parentRoute: typeof AuthenticatedDebugRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/admin/users': {
      id: '/_authenticated/settings/admin/users'
      path: '/admin/users'
      fullPath: '/settings/admin/users'
      preLoaderRoute: typeof AuthenticatedSettingsAdminUsersImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDebugRouteRouteChildren {
  AuthenticatedDebugKanbanRoute: typeof AuthenticatedDebugKanbanRoute
  AuthenticatedDebugReactflowPositioningRoute: typeof AuthenticatedDebugReactflowPositioningRoute
  AuthenticatedDebugStateMachineTestRoute: typeof AuthenticatedDebugStateMachineTestRoute
  AuthenticatedDebugVibeganttRoute: typeof AuthenticatedDebugVibeganttRoute
  AuthenticatedDebugVibegriddexTestRoute: typeof AuthenticatedDebugVibegriddexTestRoute
  AuthenticatedDebugDatabaseLazyRoute: typeof AuthenticatedDebugDatabaseLazyRoute
  AuthenticatedDebugIntegrityLazyRoute: typeof AuthenticatedDebugIntegrityLazyRoute
  AuthenticatedDebugSyncLazyRoute: typeof AuthenticatedDebugSyncLazyRoute
  AuthenticatedDebugSyncTestLazyRoute: typeof AuthenticatedDebugSyncTestLazyRoute
  AuthenticatedDebugIndexRoute: typeof AuthenticatedDebugIndexRoute
}

const AuthenticatedDebugRouteRouteChildren: AuthenticatedDebugRouteRouteChildren =
  {
    AuthenticatedDebugKanbanRoute: AuthenticatedDebugKanbanRoute,
    AuthenticatedDebugReactflowPositioningRoute:
      AuthenticatedDebugReactflowPositioningRoute,
    AuthenticatedDebugStateMachineTestRoute:
      AuthenticatedDebugStateMachineTestRoute,
    AuthenticatedDebugVibeganttRoute: AuthenticatedDebugVibeganttRoute,
    AuthenticatedDebugVibegriddexTestRoute:
      AuthenticatedDebugVibegriddexTestRoute,
    AuthenticatedDebugDatabaseLazyRoute: AuthenticatedDebugDatabaseLazyRoute,
    AuthenticatedDebugIntegrityLazyRoute: AuthenticatedDebugIntegrityLazyRoute,
    AuthenticatedDebugSyncLazyRoute: AuthenticatedDebugSyncLazyRoute,
    AuthenticatedDebugSyncTestLazyRoute: AuthenticatedDebugSyncTestLazyRoute,
    AuthenticatedDebugIndexRoute: AuthenticatedDebugIndexRoute,
  }

const AuthenticatedDebugRouteRouteWithChildren =
  AuthenticatedDebugRouteRoute._addFileChildren(
    AuthenticatedDebugRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsAdminUsersRoute: typeof AuthenticatedSettingsAdminUsersRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsAdminUsersRoute: AuthenticatedSettingsAdminUsersRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDebugRouteRoute: typeof AuthenticatedDebugRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedTasksKanbanRoute: typeof AuthenticatedTasksKanbanRoute
  AuthenticatedTasksTimelineRoute: typeof AuthenticatedTasksTimelineRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDebugRouteRoute: AuthenticatedDebugRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedTasksKanbanRoute: AuthenticatedTasksKanbanRoute,
  AuthenticatedTasksTimelineRoute: AuthenticatedTasksTimelineRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/debug': typeof AuthenticatedDebugRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/check-email': typeof authCheckEmailRoute
  '/complete-registration': typeof authCompleteRegistrationRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/otp-verify': typeof authOtpVerifyRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/reset-password/$token': typeof authResetPasswordTokenRoute
  '/debug/kanban': typeof AuthenticatedDebugKanbanRoute
  '/debug/reactflow-positioning': typeof AuthenticatedDebugReactflowPositioningRoute
  '/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/debug/vibegantt': typeof AuthenticatedDebugVibeganttRoute
  '/debug/vibegriddex-test': typeof AuthenticatedDebugVibegriddexTestRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/debug/integrity': typeof AuthenticatedDebugIntegrityLazyRoute
  '/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/debug/sync-test': typeof AuthenticatedDebugSyncTestLazyRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/debug/': typeof AuthenticatedDebugIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/settings/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
}

export interface FileRoutesByTo {
  '/check-email': typeof authCheckEmailRoute
  '/complete-registration': typeof authCompleteRegistrationRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/otp-verify': typeof authOtpVerifyRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/reset-password/$token': typeof authResetPasswordTokenRoute
  '/debug/kanban': typeof AuthenticatedDebugKanbanRoute
  '/debug/reactflow-positioning': typeof AuthenticatedDebugReactflowPositioningRoute
  '/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/debug/vibegantt': typeof AuthenticatedDebugVibeganttRoute
  '/debug/vibegriddex-test': typeof AuthenticatedDebugVibegriddexTestRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/debug/integrity': typeof AuthenticatedDebugIntegrityLazyRoute
  '/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/debug/sync-test': typeof AuthenticatedDebugSyncTestLazyRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/debug': typeof AuthenticatedDebugIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/settings/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/debug': typeof AuthenticatedDebugRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/check-email': typeof authCheckEmailRoute
  '/(auth)/complete-registration': typeof authCompleteRegistrationRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/otp-verify': typeof authOtpVerifyRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/(auth)/reset-password/$token': typeof authResetPasswordTokenRoute
  '/_authenticated/debug/kanban': typeof AuthenticatedDebugKanbanRoute
  '/_authenticated/debug/reactflow-positioning': typeof AuthenticatedDebugReactflowPositioningRoute
  '/_authenticated/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/_authenticated/debug/vibegantt': typeof AuthenticatedDebugVibeganttRoute
  '/_authenticated/debug/vibegriddex-test': typeof AuthenticatedDebugVibegriddexTestRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/_authenticated/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/_authenticated/debug/database': typeof AuthenticatedDebugDatabaseLazyRoute
  '/_authenticated/debug/integrity': typeof AuthenticatedDebugIntegrityLazyRoute
  '/_authenticated/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/_authenticated/debug/sync-test': typeof AuthenticatedDebugSyncTestLazyRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/debug/': typeof AuthenticatedDebugIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/settings/admin/users': typeof AuthenticatedSettingsAdminUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/debug'
    | '/settings'
    | '/check-email'
    | '/complete-registration'
    | '/forgot-password'
    | '/otp'
    | '/otp-verify'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/reset-password/$token'
    | '/debug/kanban'
    | '/debug/reactflow-positioning'
    | '/debug/state-machine-test'
    | '/debug/vibegantt'
    | '/debug/vibegriddex-test'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/tasks/kanban'
    | '/tasks/timeline'
    | '/debug/database'
    | '/debug/integrity'
    | '/debug/sync'
    | '/debug/sync-test'
    | '/apps'
    | '/chats'
    | '/debug/'
    | '/help-center'
    | '/projects'
    | '/settings/'
    | '/tasks'
    | '/settings/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/check-email'
    | '/complete-registration'
    | '/forgot-password'
    | '/otp'
    | '/otp-verify'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/reset-password/$token'
    | '/debug/kanban'
    | '/debug/reactflow-positioning'
    | '/debug/state-machine-test'
    | '/debug/vibegantt'
    | '/debug/vibegriddex-test'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/tasks/kanban'
    | '/tasks/timeline'
    | '/debug/database'
    | '/debug/integrity'
    | '/debug/sync'
    | '/debug/sync-test'
    | '/apps'
    | '/chats'
    | '/debug'
    | '/help-center'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/settings/admin/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/debug'
    | '/_authenticated/settings'
    | '/(auth)/check-email'
    | '/(auth)/complete-registration'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/otp-verify'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/(auth)/reset-password/$token'
    | '/_authenticated/debug/kanban'
    | '/_authenticated/debug/reactflow-positioning'
    | '/_authenticated/debug/state-machine-test'
    | '/_authenticated/debug/vibegantt'
    | '/_authenticated/debug/vibegriddex-test'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/tasks/kanban'
    | '/_authenticated/tasks/timeline'
    | '/_authenticated/debug/database'
    | '/_authenticated/debug/integrity'
    | '/_authenticated/debug/sync'
    | '/_authenticated/debug/sync-test'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/debug/'
    | '/_authenticated/help-center/'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/settings/admin/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authCheckEmailRoute: typeof authCheckEmailRoute
  authCompleteRegistrationRoute: typeof authCompleteRegistrationRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authOtpVerifyRoute: typeof authOtpVerifyRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  authResetPasswordTokenRoute: typeof authResetPasswordTokenRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authCheckEmailRoute: authCheckEmailRoute,
  authCompleteRegistrationRoute: authCompleteRegistrationRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authOtpVerifyRoute: authOtpVerifyRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  authResetPasswordTokenRoute: authResetPasswordTokenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/check-email",
        "/(auth)/complete-registration",
        "/(auth)/forgot-password",
        "/(auth)/otp",
        "/(auth)/otp-verify",
        "/(auth)/sign-in",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(auth)/verify-email",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/(auth)/reset-password/$token"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/debug",
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/projects/$projectId",
        "/_authenticated/tasks/kanban",
        "/_authenticated/tasks/timeline",
        "/_authenticated/apps/",
        "/_authenticated/chats/",
        "/_authenticated/help-center/",
        "/_authenticated/projects/",
        "/_authenticated/tasks/"
      ]
    },
    "/_authenticated/debug": {
      "filePath": "_authenticated/debug/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/debug/kanban",
        "/_authenticated/debug/reactflow-positioning",
        "/_authenticated/debug/state-machine-test",
        "/_authenticated/debug/vibegantt",
        "/_authenticated/debug/vibegriddex-test",
        "/_authenticated/debug/database",
        "/_authenticated/debug/integrity",
        "/_authenticated/debug/sync",
        "/_authenticated/debug/sync-test",
        "/_authenticated/debug/"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/",
        "/_authenticated/settings/admin/users"
      ]
    },
    "/(auth)/check-email": {
      "filePath": "(auth)/check-email.tsx"
    },
    "/(auth)/complete-registration": {
      "filePath": "(auth)/complete-registration.tsx"
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/otp-verify": {
      "filePath": "(auth)/otp-verify.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(auth)/verify-email": {
      "filePath": "(auth)/verify-email.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/reset-password/$token": {
      "filePath": "(auth)/reset-password.$token.tsx"
    },
    "/_authenticated/debug/kanban": {
      "filePath": "_authenticated/debug/kanban.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/reactflow-positioning": {
      "filePath": "_authenticated/debug/reactflow-positioning.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/state-machine-test": {
      "filePath": "_authenticated/debug/state-machine-test.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/vibegantt": {
      "filePath": "_authenticated/debug/vibegantt.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/vibegriddex-test": {
      "filePath": "_authenticated/debug/vibegriddex-test.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/projects/$projectId": {
      "filePath": "_authenticated/projects/$projectId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tasks/kanban": {
      "filePath": "_authenticated/tasks/kanban.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tasks/timeline": {
      "filePath": "_authenticated/tasks/timeline.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/debug/database": {
      "filePath": "_authenticated/debug/database.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/integrity": {
      "filePath": "_authenticated/debug/integrity.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/sync": {
      "filePath": "_authenticated/debug/sync.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/debug/sync-test": {
      "filePath": "_authenticated/debug/sync-test.lazy.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/debug/": {
      "filePath": "_authenticated/debug/index.tsx",
      "parent": "/_authenticated/debug"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/": {
      "filePath": "_authenticated/projects/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/admin/users": {
      "filePath": "_authenticated/settings/admin.users.tsx",
      "parent": "/_authenticated/settings"
    }
  }
}
ROUTE_MANIFEST_END */
