import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialLocalSchema1753895985468 implements MigrationInterface {
    name = 'InitialLocalSchema1753895985468'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "identifier" text NOT NULL, "value" text NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2127ad1b143cf012280390b01d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sync_metadata" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "client_id" text NOT NULL, "current_lsn" text NOT NULL DEFAULT '0/0', "sync_state" text NOT NULL DEFAULT 'disconnected', "last_sync_time" TIMESTAMP WITH TIME ZONE, "pending_changes_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_fbdfc072a3e60cc5086d9d84b05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "local_changes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "table" text NOT NULL, "operation" text NOT NULL, "data" jsonb NOT NULL, "lsn" text NOT NULL, "clientSequence" text, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "processed_sync" integer NOT NULL DEFAULT '0', "send_attempts" integer NOT NULL DEFAULT '0', "last_send_attempt" TIMESTAMP WITH TIME ZONE, "last_error" text, CONSTRAINT "PK_183aaeba20c9012ea8d4f54a8bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9a1987ae0b1a690d834926fe8" ON "local_changes" ("processed_sync") `);
        await queryRunner.query(`CREATE TABLE "jwks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "publicKey" text NOT NULL, "privateKey" text NOT NULL, CONSTRAINT "PK_147086b49bf8366682d1a7ca7c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_migration" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "migration_name" text NOT NULL, "schema_version" text NOT NULL, "up_queries" text array NOT NULL, "down_queries" text array NOT NULL, "description" text, "timestamp" bigint NOT NULL, CONSTRAINT "PK_3722f14cd336d56c1d65d7c3778" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bfd1577edbebf606d654aca741" ON "client_migration" ("schema_version") `);
        await queryRunner.query(`CREATE TABLE "change_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lsn" text NOT NULL, "table_name" text NOT NULL, "operation" text NOT NULL, "data" jsonb, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT "PK_6e83e27c48283592150c85d6827" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97c51ed35fb20c52eb27af19c7" ON "change_history" ("lsn") `);
        await queryRunner.query(`CREATE TABLE "status_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "status_set_id" uuid NOT NULL, "name" character varying(50) NOT NULL, "label" character varying(100) NOT NULL, "color" character varying(7) NOT NULL, "icon" character varying(50), "variant" character varying(20), "sort_order" integer NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "is_final" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "allowed_transitions" uuid array, "auto_transition_days" integer, "metadata" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_b0ace56b8b4d1c193813bb9f308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status_sets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "entityType" character varying(50) NOT NULL, "description" text, "isSystem" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "default_color" character varying(7), "display_order" integer NOT NULL DEFAULT '0', "metadata" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_f41ed2fcb721a04481e85515d7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tag_set_id" uuid NOT NULL, "name" character varying(50) NOT NULL, "slug" character varying(50) NOT NULL, "color" character varying(7) NOT NULL, "icon" character varying(50), "variant" character varying(20) NOT NULL DEFAULT 'solid', "sort_order" integer NOT NULL DEFAULT '0', "parent_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "usage_count" integer NOT NULL DEFAULT '0', "last_used_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "UQ_b3aa10c29ea4e61a830362bd25a" UNIQUE ("slug"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tag_sets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "description" text, "category" character varying(50), "is_system" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "default_color" character varying(7) NOT NULL DEFAULT '#94a3b8', "display_order" integer NOT NULL DEFAULT '0', "is_exclusive" boolean NOT NULL DEFAULT false, "max_tags" integer, "metadata" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_ae758f64e111877a639b5a4dad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('active', 'in_progress', 'completed', 'on_hold')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "description" text, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'active', "owner_id" uuid, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_legacy_status_enum" AS ENUM('open', 'in_progress', 'completed')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying(100) NOT NULL, "description" text, "legacy_status" "public"."tasks_legacy_status_enum" DEFAULT 'open', "status_id" uuid, "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'medium', "due_date" TIMESTAMP WITH TIME ZONE, "start_date" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "time_range" tsrange, "estimated_duration" interval, "legacy_tags" text array DEFAULT '{}', "project_id" uuid, "assignee_id" uuid, CONSTRAINT "chk_task_start_date_before_due_date" CHECK (("start_date" IS NULL OR "due_date" IS NULL) OR ("start_date" < "due_date")), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "token" text NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ip_address" text, "user_agent" text, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e9f62f5dcb8a54b84234c9e7a06" UNIQUE ("token"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "account_id" text NOT NULL, "provider_id" text NOT NULL, "access_token" text, "refresh_token" text, "id_token" text, "access_token_expires_at" TIMESTAMP WITH TIME ZONE, "refresh_token_expires_at" TIMESTAMP WITH TIME ZONE, "scope" text, "password" text, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'member', 'viewer', 'super_admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "email_verified" boolean NOT NULL DEFAULT false, "image" character varying(255), "role" "public"."users_role_enum" NOT NULL DEFAULT 'member', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."client_migration_status_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'failed', 'rolled_back')`);
        await queryRunner.query(`CREATE TABLE "client_migration_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "migration_name" text NOT NULL, "schema_version" text NOT NULL, "status" "public"."client_migration_status_status_enum" NOT NULL, "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "error_message" text, "attempts" integer NOT NULL DEFAULT '0', "timestamp" bigint NOT NULL, CONSTRAINT "PK_c36ad25534183aea155df9ca89d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f6a012ebab7ea3ff10fa8f3c58" ON "client_migration_status" ("schema_version") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content" text NOT NULL, "author_id" uuid, "parent_id" uuid, "task_id" uuid, "project_id" uuid, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_members" ("project_id" uuid NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_b3f491d3a3f986106d281d8eb4b" PRIMARY KEY ("project_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5729113570c20c7e214cf3f58" ON "project_members" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e89aae80e010c2faa72e6a49ce" ON "project_members" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "project_status_sets" ("project_id" uuid NOT NULL, "status_set_id" uuid NOT NULL, CONSTRAINT "PK_df26f812b71c869d8a39cc39980" PRIMARY KEY ("project_id", "status_set_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f3ca6851fd53ff904e9ce21468" ON "project_status_sets" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_968a062c0e1a4d13e351c522ba" ON "project_status_sets" ("status_set_id") `);
        await queryRunner.query(`CREATE TABLE "project_tag_sets" ("project_id" uuid NOT NULL, "tag_set_id" uuid NOT NULL, CONSTRAINT "PK_e63ae6baa6ca7e4acee6f88a26f" PRIMARY KEY ("project_id", "tag_set_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb354bb259bbd85f63d7e120eb" ON "project_tag_sets" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c558e4e6f9e753f369582865c4" ON "project_tag_sets" ("tag_set_id") `);
        await queryRunner.query(`CREATE TABLE "task_tags" ("task_id" uuid NOT NULL, "tag_id" uuid NOT NULL, CONSTRAINT "PK_a7354e3c3f630636f6e4a29694a" PRIMARY KEY ("task_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70515bc464901781ac60b82a1e" ON "task_tags" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f883135d033e1541f6a81972e7" ON "task_tags" ("tag_id") `);
        await queryRunner.query(`CREATE TABLE "task_dependencies" ("dependent_task_id" uuid NOT NULL, "dependency_task_id" uuid NOT NULL, CONSTRAINT "PK_71b0636f4fd9b1536100fc28e16" PRIMARY KEY ("dependent_task_id", "dependency_task_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_edffc2045be39cc292fe4abedd" ON "task_dependencies" ("dependent_task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba14d140f4b3a79b3b1f475de5" ON "task_dependencies" ("dependency_task_id") `);
        await queryRunner.query(`ALTER TABLE "status_definitions" ADD CONSTRAINT "FK_7bb8172ef1f90ff91d0c86d23ba" FOREIGN KEY ("status_set_id") REFERENCES "status_sets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_1b9d2591f78033221d6b7c726b6" FOREIGN KEY ("tag_set_id") REFERENCES "tag_sets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_bd19ddcde86ca1882599dbace11" FOREIGN KEY ("parent_id") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e28288969fa7827bd12680cfe10" FOREIGN KEY ("status_id") REFERENCES "status_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_855d484825b715c545349212c7f" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_3000dad1da61b29953f07476324" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_d6f93329801a93536da4241e386" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_18c2493067c11f44efb35ca0e03" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_03dbde2ff570596e874bb3bb311" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_sets" ADD CONSTRAINT "FK_f3ca6851fd53ff904e9ce214681" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_status_sets" ADD CONSTRAINT "FK_968a062c0e1a4d13e351c522ba4" FOREIGN KEY ("status_set_id") REFERENCES "status_sets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_tag_sets" ADD CONSTRAINT "FK_cb354bb259bbd85f63d7e120eb8" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_tag_sets" ADD CONSTRAINT "FK_c558e4e6f9e753f369582865c4b" FOREIGN KEY ("tag_set_id") REFERENCES "tag_sets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "FK_70515bc464901781ac60b82a1ea" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_tags" ADD CONSTRAINT "FK_f883135d033e1541f6a81972e7d" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_edffc2045be39cc292fe4abedde" FOREIGN KEY ("dependent_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_ba14d140f4b3a79b3b1f475de57" FOREIGN KEY ("dependency_task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_ba14d140f4b3a79b3b1f475de57"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_edffc2045be39cc292fe4abedde"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "FK_f883135d033e1541f6a81972e7d"`);
        await queryRunner.query(`ALTER TABLE "task_tags" DROP CONSTRAINT "FK_70515bc464901781ac60b82a1ea"`);
        await queryRunner.query(`ALTER TABLE "project_tag_sets" DROP CONSTRAINT "FK_c558e4e6f9e753f369582865c4b"`);
        await queryRunner.query(`ALTER TABLE "project_tag_sets" DROP CONSTRAINT "FK_cb354bb259bbd85f63d7e120eb8"`);
        await queryRunner.query(`ALTER TABLE "project_status_sets" DROP CONSTRAINT "FK_968a062c0e1a4d13e351c522ba4"`);
        await queryRunner.query(`ALTER TABLE "project_status_sets" DROP CONSTRAINT "FK_f3ca6851fd53ff904e9ce214681"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_03dbde2ff570596e874bb3bb311"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_18c2493067c11f44efb35ca0e03"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_d6f93329801a93536da4241e386"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_3000dad1da61b29953f07476324"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_855d484825b715c545349212c7f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e28288969fa7827bd12680cfe10"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_bd19ddcde86ca1882599dbace11"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_1b9d2591f78033221d6b7c726b6"`);
        await queryRunner.query(`ALTER TABLE "status_definitions" DROP CONSTRAINT "FK_7bb8172ef1f90ff91d0c86d23ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba14d140f4b3a79b3b1f475de5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edffc2045be39cc292fe4abedd"`);
        await queryRunner.query(`DROP TABLE "task_dependencies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f883135d033e1541f6a81972e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70515bc464901781ac60b82a1e"`);
        await queryRunner.query(`DROP TABLE "task_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c558e4e6f9e753f369582865c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb354bb259bbd85f63d7e120eb"`);
        await queryRunner.query(`DROP TABLE "project_tag_sets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_968a062c0e1a4d13e351c522ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3ca6851fd53ff904e9ce21468"`);
        await queryRunner.query(`DROP TABLE "project_status_sets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e89aae80e010c2faa72e6a49ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5729113570c20c7e214cf3f58"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6a012ebab7ea3ff10fa8f3c58"`);
        await queryRunner.query(`DROP TABLE "client_migration_status"`);
        await queryRunner.query(`DROP TYPE "public"."client_migration_status_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_legacy_status_enum"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP TABLE "tag_sets"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "status_sets"`);
        await queryRunner.query(`DROP TABLE "status_definitions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97c51ed35fb20c52eb27af19c7"`);
        await queryRunner.query(`DROP TABLE "change_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfd1577edbebf606d654aca741"`);
        await queryRunner.query(`DROP TABLE "client_migration"`);
        await queryRunner.query(`DROP TABLE "jwks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9a1987ae0b1a690d834926fe8"`);
        await queryRunner.query(`DROP TABLE "local_changes"`);
        await queryRunner.query(`DROP TABLE "sync_metadata"`);
        await queryRunner.query(`DROP TABLE "verifications"`);
    }

}
