#!/bin/bash

# Single source of truth for worktree environment configuration
# This script sets up all environment variables and saves them to .env.local
# All other scripts should source .env.local instead of calculating ports

set -e

# Detect issue number from branch or directory
detect_issue_number() {
    # 1. Environment variable (manual override)
    if [ -n "${PR_NUMBER:-}" ]; then
        echo "$PR_NUMBER"
        return
    fi
    
    # 2. Git branch name (issue-123, feature-456, pr-789)
    if command -v git &> /dev/null; then
        local branch=$(git branch --show-current 2>/dev/null || true)
        if [[ "$branch" =~ (issue-|feature-|pr-)([0-9]+) ]]; then
            echo "${BASH_REMATCH[2]}"
            return
        fi
    fi
    
    # 3. Working directory name (worktrees/issue-123)
    local cwd=$(pwd)
    if [[ "$cwd" =~ /issue-([0-9]+) ]]; then
        echo "${BASH_REMATCH[1]}"
        return
    fi
    
    # Default to main
    echo "0"
}

# Get issue number
ISSUE_NUMBER=$(detect_issue_number)

echo "🔧 Configuring environment for Issue #${ISSUE_NUMBER}"

# Calculate ports - single source of truth
if [ "$ISSUE_NUMBER" = "0" ]; then
    # Main branch uses default ports
    WEB_PORT=5173
    SERVER_PORT=8787
    DB_PORT=5432
    PROXY_PORT=4444
    DB_NAME="vibestack_dev"
else
    # Worktrees use issue number as offset
    WEB_PORT=$((5173 + ISSUE_NUMBER))
    SERVER_PORT=$((8787 + ISSUE_NUMBER))
    DB_PORT=$((5432 + ISSUE_NUMBER))
    PROXY_PORT=$((4444 + ISSUE_NUMBER))
    DB_NAME="vibestack_dev_issue_${ISSUE_NUMBER}"
fi

# Backup existing .env.local if it exists
if [ -f .env.local ]; then
    mv .env.local .env.local.bak
fi

# Create .env.local with all configuration
cat > .env.local << EOF
# Worktree Configuration - Issue #${ISSUE_NUMBER}
# Generated by configure-worktree-env.sh
# This is the SINGLE SOURCE OF TRUTH for all port configuration

# Port Configuration
WEB_PORT=${WEB_PORT}
SERVER_PORT=${SERVER_PORT}
DB_PORT=${DB_PORT}
PROXY_PORT=${PROXY_PORT}

# Issue/PR Number
PR_NUMBER=${ISSUE_NUMBER}
ISSUE_NUMBER=${ISSUE_NUMBER}

# Database Configuration
DATABASE_URL=postgres://postgres:postgres@localhost:${DB_PORT}/${DB_NAME}
DATABASE_NAME=${DB_NAME}

# API URLs
VITE_API_URL=http://127.0.0.1:${SERVER_PORT}
API_URL=http://localhost:${SERVER_PORT}

EOF

# Preserve Playwright credentials if they exist
if [ -f .env.local.bak ]; then
    echo "" >> .env.local
    echo "# Playwright Test Credentials (preserved)" >> .env.local
    grep "VIBE_DEV_EMAIL\|VIBE_DEV_PASSWORD" .env.local.bak >> .env.local 2>/dev/null || true
fi

# Update apps/web/.env.development with correct API URL
if [ -f apps/web/.env.development ]; then
    # Create backup
    cp apps/web/.env.development apps/web/.env.development.bak
    
    # Update the API URL
    sed -i "s|VITE_API_URL=.*|VITE_API_URL=http://127.0.0.1:${SERVER_PORT}|" apps/web/.env.development
    echo "✅ Updated apps/web/.env.development"
fi

# Update apps/server/.dev.vars if needed (for local database URL)
if [ -f apps/server/.dev.vars ]; then
    # Check if LOCAL_DATABASE_URL exists, if not add it
    if ! grep -q "LOCAL_DATABASE_URL" apps/server/.dev.vars; then
        echo "" >> apps/server/.dev.vars
        echo "# Local database for this worktree" >> apps/server/.dev.vars
        echo "LOCAL_DATABASE_URL=postgres://postgres:postgres@localhost:${DB_PORT}/${DB_NAME}" >> apps/server/.dev.vars
    else
        # Update existing LOCAL_DATABASE_URL
        sed -i "s|LOCAL_DATABASE_URL=.*|LOCAL_DATABASE_URL=postgres://postgres:postgres@localhost:${DB_PORT}/${DB_NAME}|" apps/server/.dev.vars
    fi
    echo "✅ Updated apps/server/.dev.vars"
fi

echo ""
echo "✅ Environment configuration complete!"
echo ""
echo "📊 Configuration saved to .env.local:"
echo "   Web Port:    ${WEB_PORT}"
echo "   Server Port: ${SERVER_PORT}"
echo "   DB Port:     ${DB_PORT}"
echo "   Proxy Port:  ${PROXY_PORT}"
echo "   Database:    ${DB_NAME}"
echo ""
echo "🚀 Services will be available at:"
echo "   Web: http://localhost:${WEB_PORT}"
echo "   API: http://localhost:${SERVER_PORT}"
echo ""
echo "📝 All scripts will now use these settings from .env.local"