/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpVerifyRouteImport } from './routes/(auth)/otp-verify'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authCompleteRegistrationRouteImport } from './routes/(auth)/complete-registration'
import { Route as authCheckEmailRouteImport } from './routes/(auth)/check-email'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDebugRouteRouteImport } from './routes/_authenticated/debug/route'
import { Route as AuthenticatedUniverseIndexRouteImport } from './routes/_authenticated/universe/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPlatformAdminIndexRouteImport } from './routes/_authenticated/platform-admin/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedEntitiesIndexRouteImport } from './routes/_authenticated/entities/index'
import { Route as AuthenticatedDebugIndexRouteImport } from './routes/_authenticated/debug/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedUniverseDetailRouteImport } from './routes/_authenticated/universe/detail'
import { Route as AuthenticatedTasksTimelineRouteImport } from './routes/_authenticated/tasks/timeline'
import { Route as AuthenticatedTasksKanbanRouteImport } from './routes/_authenticated/tasks/kanban'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedPlatformAdminUsersRouteImport } from './routes/_authenticated/platform-admin/users'
import { Route as AuthenticatedPlatformAdminOrganizationsRouteImport } from './routes/_authenticated/platform-admin/organizations'
import { Route as AuthenticatedPlatformAdminFeatureFlagsRouteImport } from './routes/_authenticated/platform-admin/feature-flags'
import { Route as AuthenticatedDebugVibegridLegendStateRouteImport } from './routes/_authenticated/debug/vibegrid-legend-state'
import { Route as AuthenticatedDebugVibeganttTestRouteImport } from './routes/_authenticated/debug/vibegantt-test'
import { Route as AuthenticatedDebugVibeganttRouteImport } from './routes/_authenticated/debug/vibegantt'
import { Route as AuthenticatedDebugSystemOptionsRouteImport } from './routes/_authenticated/debug/system-options'
import { Route as AuthenticatedDebugStateMachineTestRouteImport } from './routes/_authenticated/debug/state-machine-test'
import { Route as AuthenticatedDebugLocalStorageSyncRouteImport } from './routes/_authenticated/debug/local-storage-sync'
import { Route as AuthenticatedDebugLegendStateTestRouteImport } from './routes/_authenticated/debug/legend-state-test'
import { Route as AuthenticatedOrgOrgIdIndexRouteImport } from './routes/_authenticated/org/$orgId/index'
import { Route as AuthenticatedOrgOrgIdTestPassiveRendererRouteImport } from './routes/_authenticated/org/$orgId/test-passive-renderer'
import { Route as AuthenticatedOrgOrgIdDashboardRouteImport } from './routes/_authenticated/org/$orgId/dashboard'
import { Route as AuthenticatedOrgOrgIdEntitiesEntityNameRouteImport } from './routes/_authenticated/org/$orgId/entities/$entityName'

const AuthenticatedDebugSyncLazyRouteImport = createFileRoute(
  '/_authenticated/debug/sync',
)()
const AuthenticatedDebugEntityOperationsLazyRouteImport = createFileRoute(
  '/_authenticated/debug/entity-operations',
)()

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpVerifyRoute = authOtpVerifyRouteImport.update({
  id: '/(auth)/otp-verify',
  path: '/otp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/(auth)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authCompleteRegistrationRoute =
  authCompleteRegistrationRouteImport.update({
    id: '/(auth)/complete-registration',
    path: '/complete-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const authCheckEmailRoute = authCheckEmailRouteImport.update({
  id: '/(auth)/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugRouteRoute = AuthenticatedDebugRouteRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUniverseIndexRoute =
  AuthenticatedUniverseIndexRouteImport.update({
    id: '/universe/',
    path: '/universe/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPlatformAdminIndexRoute =
  AuthenticatedPlatformAdminIndexRouteImport.update({
    id: '/platform-admin/',
    path: '/platform-admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntitiesIndexRoute =
  AuthenticatedEntitiesIndexRouteImport.update({
    id: '/entities/',
    path: '/entities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugIndexRoute = AuthenticatedDebugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDebugRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebugSyncLazyRoute =
  AuthenticatedDebugSyncLazyRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/sync.lazy').then((d) => d.Route),
  )
const AuthenticatedDebugEntityOperationsLazyRoute =
  AuthenticatedDebugEntityOperationsLazyRouteImport.update({
    id: '/entity-operations',
    path: '/entity-operations',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/debug/entity-operations.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUniverseDetailRoute =
  AuthenticatedUniverseDetailRouteImport.update({
    id: '/universe/detail',
    path: '/universe/detail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksTimelineRoute =
  AuthenticatedTasksTimelineRouteImport.update({
    id: '/tasks/timeline',
    path: '/tasks/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksKanbanRoute =
  AuthenticatedTasksKanbanRouteImport.update({
    id: '/tasks/kanban',
    path: '/tasks/kanban',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformAdminUsersRoute =
  AuthenticatedPlatformAdminUsersRouteImport.update({
    id: '/platform-admin/users',
    path: '/platform-admin/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformAdminOrganizationsRoute =
  AuthenticatedPlatformAdminOrganizationsRouteImport.update({
    id: '/platform-admin/organizations',
    path: '/platform-admin/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformAdminFeatureFlagsRoute =
  AuthenticatedPlatformAdminFeatureFlagsRouteImport.update({
    id: '/platform-admin/feature-flags',
    path: '/platform-admin/feature-flags',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugVibegridLegendStateRoute =
  AuthenticatedDebugVibegridLegendStateRouteImport.update({
    id: '/vibegrid-legend-state',
    path: '/vibegrid-legend-state',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugVibeganttTestRoute =
  AuthenticatedDebugVibeganttTestRouteImport.update({
    id: '/vibegantt-test',
    path: '/vibegantt-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugVibeganttRoute =
  AuthenticatedDebugVibeganttRouteImport.update({
    id: '/vibegantt',
    path: '/vibegantt',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugSystemOptionsRoute =
  AuthenticatedDebugSystemOptionsRouteImport.update({
    id: '/system-options',
    path: '/system-options',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugStateMachineTestRoute =
  AuthenticatedDebugStateMachineTestRouteImport.update({
    id: '/state-machine-test',
    path: '/state-machine-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugLocalStorageSyncRoute =
  AuthenticatedDebugLocalStorageSyncRouteImport.update({
    id: '/local-storage-sync',
    path: '/local-storage-sync',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedDebugLegendStateTestRoute =
  AuthenticatedDebugLegendStateTestRouteImport.update({
    id: '/legend-state-test',
    path: '/legend-state-test',
    getParentRoute: () => AuthenticatedDebugRouteRoute,
  } as any)
const AuthenticatedOrgOrgIdIndexRoute =
  AuthenticatedOrgOrgIdIndexRouteImport.update({
    id: '/org/$orgId/',
    path: '/org/$orgId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgOrgIdTestPassiveRendererRoute =
  AuthenticatedOrgOrgIdTestPassiveRendererRouteImport.update({
    id: '/org/$orgId/test-passive-renderer',
    path: '/org/$orgId/test-passive-renderer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgOrgIdDashboardRoute =
  AuthenticatedOrgOrgIdDashboardRouteImport.update({
    id: '/org/$orgId/dashboard',
    path: '/org/$orgId/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgOrgIdEntitiesEntityNameRoute =
  AuthenticatedOrgOrgIdEntitiesEntityNameRouteImport.update({
    id: '/org/$orgId/entities/$entityName',
    path: '/org/$orgId/entities/$entityName',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/debug': typeof AuthenticatedDebugRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/check-email': typeof authCheckEmailRoute
  '/complete-registration': typeof authCompleteRegistrationRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/otp': typeof authOtpRoute
  '/otp-verify': typeof authOtpVerifyRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/debug/legend-state-test': typeof AuthenticatedDebugLegendStateTestRoute
  '/debug/local-storage-sync': typeof AuthenticatedDebugLocalStorageSyncRoute
  '/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/debug/system-options': typeof AuthenticatedDebugSystemOptionsRoute
  '/debug/vibegantt': typeof AuthenticatedDebugVibeganttRoute
  '/debug/vibegantt-test': typeof AuthenticatedDebugVibeganttTestRoute
  '/debug/vibegrid-legend-state': typeof AuthenticatedDebugVibegridLegendStateRoute
  '/platform-admin/feature-flags': typeof AuthenticatedPlatformAdminFeatureFlagsRoute
  '/platform-admin/organizations': typeof AuthenticatedPlatformAdminOrganizationsRoute
  '/platform-admin/users': typeof AuthenticatedPlatformAdminUsersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/universe/detail': typeof AuthenticatedUniverseDetailRoute
  '/debug/entity-operations': typeof AuthenticatedDebugEntityOperationsLazyRoute
  '/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/debug/': typeof AuthenticatedDebugIndexRoute
  '/entities': typeof AuthenticatedEntitiesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/universe': typeof AuthenticatedUniverseIndexRoute
  '/org/$orgId/dashboard': typeof AuthenticatedOrgOrgIdDashboardRoute
  '/org/$orgId/test-passive-renderer': typeof AuthenticatedOrgOrgIdTestPassiveRendererRoute
  '/org/$orgId': typeof AuthenticatedOrgOrgIdIndexRoute
  '/org/$orgId/entities/$entityName': typeof AuthenticatedOrgOrgIdEntitiesEntityNameRoute
}
export interface FileRoutesByTo {
  '/check-email': typeof authCheckEmailRoute
  '/complete-registration': typeof authCompleteRegistrationRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/onboarding': typeof authOnboardingRoute
  '/otp': typeof authOtpRoute
  '/otp-verify': typeof authOtpVerifyRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/debug/legend-state-test': typeof AuthenticatedDebugLegendStateTestRoute
  '/debug/local-storage-sync': typeof AuthenticatedDebugLocalStorageSyncRoute
  '/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/debug/system-options': typeof AuthenticatedDebugSystemOptionsRoute
  '/debug/vibegantt': typeof AuthenticatedDebugVibeganttRoute
  '/debug/vibegantt-test': typeof AuthenticatedDebugVibeganttTestRoute
  '/debug/vibegrid-legend-state': typeof AuthenticatedDebugVibegridLegendStateRoute
  '/platform-admin/feature-flags': typeof AuthenticatedPlatformAdminFeatureFlagsRoute
  '/platform-admin/organizations': typeof AuthenticatedPlatformAdminOrganizationsRoute
  '/platform-admin/users': typeof AuthenticatedPlatformAdminUsersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/universe/detail': typeof AuthenticatedUniverseDetailRoute
  '/debug/entity-operations': typeof AuthenticatedDebugEntityOperationsLazyRoute
  '/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/debug': typeof AuthenticatedDebugIndexRoute
  '/entities': typeof AuthenticatedEntitiesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/universe': typeof AuthenticatedUniverseIndexRoute
  '/org/$orgId/dashboard': typeof AuthenticatedOrgOrgIdDashboardRoute
  '/org/$orgId/test-passive-renderer': typeof AuthenticatedOrgOrgIdTestPassiveRendererRoute
  '/org/$orgId': typeof AuthenticatedOrgOrgIdIndexRoute
  '/org/$orgId/entities/$entityName': typeof AuthenticatedOrgOrgIdEntitiesEntityNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/debug': typeof AuthenticatedDebugRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/check-email': typeof authCheckEmailRoute
  '/(auth)/complete-registration': typeof authCompleteRegistrationRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/otp-verify': typeof authOtpVerifyRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/debug/legend-state-test': typeof AuthenticatedDebugLegendStateTestRoute
  '/_authenticated/debug/local-storage-sync': typeof AuthenticatedDebugLocalStorageSyncRoute
  '/_authenticated/debug/state-machine-test': typeof AuthenticatedDebugStateMachineTestRoute
  '/_authenticated/debug/system-options': typeof AuthenticatedDebugSystemOptionsRoute
  '/_authenticated/debug/vibegantt': typeof AuthenticatedDebugVibeganttRoute
  '/_authenticated/debug/vibegantt-test': typeof AuthenticatedDebugVibeganttTestRoute
  '/_authenticated/debug/vibegrid-legend-state': typeof AuthenticatedDebugVibegridLegendStateRoute
  '/_authenticated/platform-admin/feature-flags': typeof AuthenticatedPlatformAdminFeatureFlagsRoute
  '/_authenticated/platform-admin/organizations': typeof AuthenticatedPlatformAdminOrganizationsRoute
  '/_authenticated/platform-admin/users': typeof AuthenticatedPlatformAdminUsersRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/tasks/kanban': typeof AuthenticatedTasksKanbanRoute
  '/_authenticated/tasks/timeline': typeof AuthenticatedTasksTimelineRoute
  '/_authenticated/universe/detail': typeof AuthenticatedUniverseDetailRoute
  '/_authenticated/debug/entity-operations': typeof AuthenticatedDebugEntityOperationsLazyRoute
  '/_authenticated/debug/sync': typeof AuthenticatedDebugSyncLazyRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/debug/': typeof AuthenticatedDebugIndexRoute
  '/_authenticated/entities/': typeof AuthenticatedEntitiesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/platform-admin/': typeof AuthenticatedPlatformAdminIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/universe/': typeof AuthenticatedUniverseIndexRoute
  '/_authenticated/org/$orgId/dashboard': typeof AuthenticatedOrgOrgIdDashboardRoute
  '/_authenticated/org/$orgId/test-passive-renderer': typeof AuthenticatedOrgOrgIdTestPassiveRendererRoute
  '/_authenticated/org/$orgId/': typeof AuthenticatedOrgOrgIdIndexRoute
  '/_authenticated/org/$orgId/entities/$entityName': typeof AuthenticatedOrgOrgIdEntitiesEntityNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/debug'
    | '/settings'
    | '/check-email'
    | '/complete-registration'
    | '/forgot-password'
    | '/onboarding'
    | '/otp'
    | '/otp-verify'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/debug/legend-state-test'
    | '/debug/local-storage-sync'
    | '/debug/state-machine-test'
    | '/debug/system-options'
    | '/debug/vibegantt'
    | '/debug/vibegantt-test'
    | '/debug/vibegrid-legend-state'
    | '/platform-admin/feature-flags'
    | '/platform-admin/organizations'
    | '/platform-admin/users'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/notifications'
    | '/settings/organization'
    | '/tasks/kanban'
    | '/tasks/timeline'
    | '/universe/detail'
    | '/debug/entity-operations'
    | '/debug/sync'
    | '/apps'
    | '/chats'
    | '/debug/'
    | '/entities'
    | '/help-center'
    | '/platform-admin'
    | '/settings/'
    | '/tasks'
    | '/universe'
    | '/org/$orgId/dashboard'
    | '/org/$orgId/test-passive-renderer'
    | '/org/$orgId'
    | '/org/$orgId/entities/$entityName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/check-email'
    | '/complete-registration'
    | '/forgot-password'
    | '/onboarding'
    | '/otp'
    | '/otp-verify'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/debug/legend-state-test'
    | '/debug/local-storage-sync'
    | '/debug/state-machine-test'
    | '/debug/system-options'
    | '/debug/vibegantt'
    | '/debug/vibegantt-test'
    | '/debug/vibegrid-legend-state'
    | '/platform-admin/feature-flags'
    | '/platform-admin/organizations'
    | '/platform-admin/users'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/notifications'
    | '/settings/organization'
    | '/tasks/kanban'
    | '/tasks/timeline'
    | '/universe/detail'
    | '/debug/entity-operations'
    | '/debug/sync'
    | '/apps'
    | '/chats'
    | '/debug'
    | '/entities'
    | '/help-center'
    | '/platform-admin'
    | '/settings'
    | '/tasks'
    | '/universe'
    | '/org/$orgId/dashboard'
    | '/org/$orgId/test-passive-renderer'
    | '/org/$orgId'
    | '/org/$orgId/entities/$entityName'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/debug'
    | '/_authenticated/settings'
    | '/(auth)/check-email'
    | '/(auth)/complete-registration'
    | '/(auth)/forgot-password'
    | '/(auth)/onboarding'
    | '/(auth)/otp'
    | '/(auth)/otp-verify'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/debug/legend-state-test'
    | '/_authenticated/debug/local-storage-sync'
    | '/_authenticated/debug/state-machine-test'
    | '/_authenticated/debug/system-options'
    | '/_authenticated/debug/vibegantt'
    | '/_authenticated/debug/vibegantt-test'
    | '/_authenticated/debug/vibegrid-legend-state'
    | '/_authenticated/platform-admin/feature-flags'
    | '/_authenticated/platform-admin/organizations'
    | '/_authenticated/platform-admin/users'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/organization'
    | '/_authenticated/tasks/kanban'
    | '/_authenticated/tasks/timeline'
    | '/_authenticated/universe/detail'
    | '/_authenticated/debug/entity-operations'
    | '/_authenticated/debug/sync'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/debug/'
    | '/_authenticated/entities/'
    | '/_authenticated/help-center/'
    | '/_authenticated/platform-admin/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/universe/'
    | '/_authenticated/org/$orgId/dashboard'
    | '/_authenticated/org/$orgId/test-passive-renderer'
    | '/_authenticated/org/$orgId/'
    | '/_authenticated/org/$orgId/entities/$entityName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authCheckEmailRoute: typeof authCheckEmailRoute
  authCompleteRegistrationRoute: typeof authCompleteRegistrationRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authOtpRoute: typeof authOtpRoute
  authOtpVerifyRoute: typeof authOtpVerifyRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp-verify': {
      id: '/(auth)/otp-verify'
      path: '/otp-verify'
      fullPath: '/otp-verify'
      preLoaderRoute: typeof authOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/complete-registration': {
      id: '/(auth)/complete-registration'
      path: '/complete-registration'
      fullPath: '/complete-registration'
      preLoaderRoute: typeof authCompleteRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/check-email': {
      id: '/(auth)/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof authCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug': {
      id: '/_authenticated/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AuthenticatedDebugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/universe/': {
      id: '/_authenticated/universe/'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof AuthenticatedUniverseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/platform-admin/': {
      id: '/_authenticated/platform-admin/'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof AuthenticatedPlatformAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities/': {
      id: '/_authenticated/entities/'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof AuthenticatedEntitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/': {
      id: '/_authenticated/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof AuthenticatedDebugIndexRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/sync': {
      id: '/_authenticated/debug/sync'
      path: '/sync'
      fullPath: '/debug/sync'
      preLoaderRoute: typeof AuthenticatedDebugSyncLazyRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/entity-operations': {
      id: '/_authenticated/debug/entity-operations'
      path: '/entity-operations'
      fullPath: '/debug/entity-operations'
      preLoaderRoute: typeof AuthenticatedDebugEntityOperationsLazyRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/universe/detail': {
      id: '/_authenticated/universe/detail'
      path: '/universe/detail'
      fullPath: '/universe/detail'
      preLoaderRoute: typeof AuthenticatedUniverseDetailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/timeline': {
      id: '/_authenticated/tasks/timeline'
      path: '/tasks/timeline'
      fullPath: '/tasks/timeline'
      preLoaderRoute: typeof AuthenticatedTasksTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/kanban': {
      id: '/_authenticated/tasks/kanban'
      path: '/tasks/kanban'
      fullPath: '/tasks/kanban'
      preLoaderRoute: typeof AuthenticatedTasksKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-admin/users': {
      id: '/_authenticated/platform-admin/users'
      path: '/platform-admin/users'
      fullPath: '/platform-admin/users'
      preLoaderRoute: typeof AuthenticatedPlatformAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-admin/organizations': {
      id: '/_authenticated/platform-admin/organizations'
      path: '/platform-admin/organizations'
      fullPath: '/platform-admin/organizations'
      preLoaderRoute: typeof AuthenticatedPlatformAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-admin/feature-flags': {
      id: '/_authenticated/platform-admin/feature-flags'
      path: '/platform-admin/feature-flags'
      fullPath: '/platform-admin/feature-flags'
      preLoaderRoute: typeof AuthenticatedPlatformAdminFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/vibegrid-legend-state': {
      id: '/_authenticated/debug/vibegrid-legend-state'
      path: '/vibegrid-legend-state'
      fullPath: '/debug/vibegrid-legend-state'
      preLoaderRoute: typeof AuthenticatedDebugVibegridLegendStateRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/vibegantt-test': {
      id: '/_authenticated/debug/vibegantt-test'
      path: '/vibegantt-test'
      fullPath: '/debug/vibegantt-test'
      preLoaderRoute: typeof AuthenticatedDebugVibeganttTestRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/vibegantt': {
      id: '/_authenticated/debug/vibegantt'
      path: '/vibegantt'
      fullPath: '/debug/vibegantt'
      preLoaderRoute: typeof AuthenticatedDebugVibeganttRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/system-options': {
      id: '/_authenticated/debug/system-options'
      path: '/system-options'
      fullPath: '/debug/system-options'
      preLoaderRoute: typeof AuthenticatedDebugSystemOptionsRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/state-machine-test': {
      id: '/_authenticated/debug/state-machine-test'
      path: '/state-machine-test'
      fullPath: '/debug/state-machine-test'
      preLoaderRoute: typeof AuthenticatedDebugStateMachineTestRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/local-storage-sync': {
      id: '/_authenticated/debug/local-storage-sync'
      path: '/local-storage-sync'
      fullPath: '/debug/local-storage-sync'
      preLoaderRoute: typeof AuthenticatedDebugLocalStorageSyncRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/debug/legend-state-test': {
      id: '/_authenticated/debug/legend-state-test'
      path: '/legend-state-test'
      fullPath: '/debug/legend-state-test'
      preLoaderRoute: typeof AuthenticatedDebugLegendStateTestRouteImport
      parentRoute: typeof AuthenticatedDebugRouteRoute
    }
    '/_authenticated/org/$orgId/': {
      id: '/_authenticated/org/$orgId/'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof AuthenticatedOrgOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/$orgId/test-passive-renderer': {
      id: '/_authenticated/org/$orgId/test-passive-renderer'
      path: '/org/$orgId/test-passive-renderer'
      fullPath: '/org/$orgId/test-passive-renderer'
      preLoaderRoute: typeof AuthenticatedOrgOrgIdTestPassiveRendererRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/$orgId/dashboard': {
      id: '/_authenticated/org/$orgId/dashboard'
      path: '/org/$orgId/dashboard'
      fullPath: '/org/$orgId/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgOrgIdDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/$orgId/entities/$entityName': {
      id: '/_authenticated/org/$orgId/entities/$entityName'
      path: '/org/$orgId/entities/$entityName'
      fullPath: '/org/$orgId/entities/$entityName'
      preLoaderRoute: typeof AuthenticatedOrgOrgIdEntitiesEntityNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDebugRouteRouteChildren {
  AuthenticatedDebugLegendStateTestRoute: typeof AuthenticatedDebugLegendStateTestRoute
  AuthenticatedDebugLocalStorageSyncRoute: typeof AuthenticatedDebugLocalStorageSyncRoute
  AuthenticatedDebugStateMachineTestRoute: typeof AuthenticatedDebugStateMachineTestRoute
  AuthenticatedDebugSystemOptionsRoute: typeof AuthenticatedDebugSystemOptionsRoute
  AuthenticatedDebugVibeganttRoute: typeof AuthenticatedDebugVibeganttRoute
  AuthenticatedDebugVibeganttTestRoute: typeof AuthenticatedDebugVibeganttTestRoute
  AuthenticatedDebugVibegridLegendStateRoute: typeof AuthenticatedDebugVibegridLegendStateRoute
  AuthenticatedDebugEntityOperationsLazyRoute: typeof AuthenticatedDebugEntityOperationsLazyRoute
  AuthenticatedDebugSyncLazyRoute: typeof AuthenticatedDebugSyncLazyRoute
  AuthenticatedDebugIndexRoute: typeof AuthenticatedDebugIndexRoute
}

const AuthenticatedDebugRouteRouteChildren: AuthenticatedDebugRouteRouteChildren =
  {
    AuthenticatedDebugLegendStateTestRoute:
      AuthenticatedDebugLegendStateTestRoute,
    AuthenticatedDebugLocalStorageSyncRoute:
      AuthenticatedDebugLocalStorageSyncRoute,
    AuthenticatedDebugStateMachineTestRoute:
      AuthenticatedDebugStateMachineTestRoute,
    AuthenticatedDebugSystemOptionsRoute: AuthenticatedDebugSystemOptionsRoute,
    AuthenticatedDebugVibeganttRoute: AuthenticatedDebugVibeganttRoute,
    AuthenticatedDebugVibeganttTestRoute: AuthenticatedDebugVibeganttTestRoute,
    AuthenticatedDebugVibegridLegendStateRoute:
      AuthenticatedDebugVibegridLegendStateRoute,
    AuthenticatedDebugEntityOperationsLazyRoute:
      AuthenticatedDebugEntityOperationsLazyRoute,
    AuthenticatedDebugSyncLazyRoute: AuthenticatedDebugSyncLazyRoute,
    AuthenticatedDebugIndexRoute: AuthenticatedDebugIndexRoute,
  }

const AuthenticatedDebugRouteRouteWithChildren =
  AuthenticatedDebugRouteRoute._addFileChildren(
    AuthenticatedDebugRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
    AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsOrganizationRoute:
      AuthenticatedSettingsOrganizationRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDebugRouteRoute: typeof AuthenticatedDebugRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPlatformAdminFeatureFlagsRoute: typeof AuthenticatedPlatformAdminFeatureFlagsRoute
  AuthenticatedPlatformAdminOrganizationsRoute: typeof AuthenticatedPlatformAdminOrganizationsRoute
  AuthenticatedPlatformAdminUsersRoute: typeof AuthenticatedPlatformAdminUsersRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedTasksKanbanRoute: typeof AuthenticatedTasksKanbanRoute
  AuthenticatedTasksTimelineRoute: typeof AuthenticatedTasksTimelineRoute
  AuthenticatedUniverseDetailRoute: typeof AuthenticatedUniverseDetailRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedEntitiesIndexRoute: typeof AuthenticatedEntitiesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedPlatformAdminIndexRoute: typeof AuthenticatedPlatformAdminIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUniverseIndexRoute: typeof AuthenticatedUniverseIndexRoute
  AuthenticatedOrgOrgIdDashboardRoute: typeof AuthenticatedOrgOrgIdDashboardRoute
  AuthenticatedOrgOrgIdTestPassiveRendererRoute: typeof AuthenticatedOrgOrgIdTestPassiveRendererRoute
  AuthenticatedOrgOrgIdIndexRoute: typeof AuthenticatedOrgOrgIdIndexRoute
  AuthenticatedOrgOrgIdEntitiesEntityNameRoute: typeof AuthenticatedOrgOrgIdEntitiesEntityNameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDebugRouteRoute: AuthenticatedDebugRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPlatformAdminFeatureFlagsRoute:
    AuthenticatedPlatformAdminFeatureFlagsRoute,
  AuthenticatedPlatformAdminOrganizationsRoute:
    AuthenticatedPlatformAdminOrganizationsRoute,
  AuthenticatedPlatformAdminUsersRoute: AuthenticatedPlatformAdminUsersRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedTasksKanbanRoute: AuthenticatedTasksKanbanRoute,
  AuthenticatedTasksTimelineRoute: AuthenticatedTasksTimelineRoute,
  AuthenticatedUniverseDetailRoute: AuthenticatedUniverseDetailRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedEntitiesIndexRoute: AuthenticatedEntitiesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedPlatformAdminIndexRoute: AuthenticatedPlatformAdminIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUniverseIndexRoute: AuthenticatedUniverseIndexRoute,
  AuthenticatedOrgOrgIdDashboardRoute: AuthenticatedOrgOrgIdDashboardRoute,
  AuthenticatedOrgOrgIdTestPassiveRendererRoute:
    AuthenticatedOrgOrgIdTestPassiveRendererRoute,
  AuthenticatedOrgOrgIdIndexRoute: AuthenticatedOrgOrgIdIndexRoute,
  AuthenticatedOrgOrgIdEntitiesEntityNameRoute:
    AuthenticatedOrgOrgIdEntitiesEntityNameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authCheckEmailRoute: authCheckEmailRoute,
  authCompleteRegistrationRoute: authCompleteRegistrationRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOnboardingRoute: authOnboardingRoute,
  authOtpRoute: authOtpRoute,
  authOtpVerifyRoute: authOtpVerifyRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
