import 'reflect-metadata';
import { getMetadataArgsStorage } from 'typeorm';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs/promises';

// Import the generated client entities
import * as ClientEntities from '../generated/client-entities.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PACKAGE_ROOT = path.resolve(__dirname, '../..');

interface RDGColumnConfig {
  cellType?: string;
  config?: Record<string, any>;
  businessLogic?: string;
  enumOptions?: Array<{ value: string; label: string }>;
  defaultValue?: any;
  cascadeConfig?: {
    onDelete?: 'CASCADE' | 'SET NULL' | 'RESTRICT';
    onUpdate?: 'CASCADE' | 'SET NULL' | 'RESTRICT';
  };
}

function pascalToWords(str: string): string {
  return str
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (match) => match.toUpperCase())
    .trim();
}

function camelToWords(str: string): string {
  return str
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (match) => match.toUpperCase())
    .trim();
}

function getDefaultWidth(cellType: string): number {
  const widths: Record<string, number> = {
    'uuid': 120,
    'date': 120,
    'number': 100,
    'boolean': 80,
    'enum': 120,
    'text': 250,
    'relationship-single': 180,
    'relationship-multi': 180,
    'relationship-collection': 200,
    'json': 220,
    'relation': 180,
    'select': 120,
    'default': 150
  };
  return widths[cellType] || widths.default;
}

function getMinWidth(cellType: string): number {
  const minWidths: Record<string, number> = {
    'uuid': 100,
    'date': 100,
    'number': 80,
    'boolean': 70,
    'enum': 100,
    'text': 120,
    'relationship-single': 140,
    'relationship-multi': 140,
    'relationship-collection': 160,
    'json': 140,
    'relation': 140,
    'select': 100,
    'default': 100
  };
  return minWidths[cellType] || minWidths.default;
}

/**
 * Main function to generate RDG column configurations
 */
async function generateRDGColumns() {
  console.log('🚀 Generating React Data Grid column configurations...');

  // Get entity schemas from the generated client entities
  const entitySchemas: any[] = [];
  const entityClasses: Function[] = [];
  
  // Extract entity schemas and classes from ClientEntities
  for (const [key, value] of Object.entries(ClientEntities)) {
    if (key.endsWith('Schema') && value && typeof value === 'object' && 'options' in value) {
      entitySchemas.push(value);
    } else if (typeof value === 'function' && value.prototype) {
      // Skip utility functions and only include entity classes
      const excludedFunctions = ['getEntityRelationships', 'hasRelationshipConfig', 'getJunctionRelationships'];
      if (!excludedFunctions.includes(key) && value.name && value.name[0] === value.name[0].toUpperCase()) {
        entityClasses.push(value as Function);
      }
    }
  }
  
  console.log('Found entity schemas:', entitySchemas.map(s => s.options?.name));
  console.log('Generating RDG columns for entities:', entityClasses.map(e => e.name));
  
  // Ensure generated directory exists
  const generatedDir = path.join(PACKAGE_ROOT, 'src/generated');
  await fs.mkdir(generatedDir, { recursive: true });
  
  // Generate RDG column configurations using the entity schemas
  const rdgColumnsOutput = generateRDGColumnConfigurations(entitySchemas, entityClasses);
  const rdgColumnsPath = path.join(generatedDir, 'rdg-column-configurations.ts');
  await fs.writeFile(rdgColumnsPath, rdgColumnsOutput);
  console.log('✅ React Data Grid column configurations generated successfully!');
  console.log(`📁 Output: ${rdgColumnsPath}`);
}

/**
 * Generate RDG column configurations from entity schemas
 */
function generateRDGColumnConfigurations(entitySchemas: any[], entityClasses: Function[]): string {
  const storage = getMetadataArgsStorage();
  
  // Generate dynamic imports based on available entity classes
  const entityImports = entityClasses.map(entityClass => entityClass.name).sort().join(',\n  ');
  
  let output = `// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
// Generated by generate-rdg-columns.ts

import React from 'react';
import type { Column } from 'react-data-grid';

export interface RDGColumnMetadata {
  cellType?: 'text' | 'number' | 'boolean' | 'date' | 'enum' | 'relationship-single' | 'relationship-multi' | 'relationship-collection' | 'uuid' | 'json';
  config?: {
    editable?: boolean;
    placeholder?: string;
    enumValues?: Record<string, string>;
    format?: string;
    showTime?: boolean;
    dateMin?: string;
    dateMax?: string;
    relationshipType?: string;
    displayField?: string;
    searchFields?: string[];
    allowCreate?: boolean;
    options?: Array<{ value: string; label: string }>;
    searchable?: boolean;
    numberMin?: number;
    numberMax?: number;
    step?: number;
    maxLength?: number;
    inputType?: string;
    targetEntity?: string;
    [key: string]: any;
  };
  businessLogic?: {
    allowedTransitions?: Record<string, string[]>;
    requiresPermission?: string;
    auditLog?: boolean;
    relationship?: boolean;
    requiresValidReference?: boolean;
    targetEntity?: string;
    sensitive?: boolean;
    maskInLogs?: boolean;
    restrictedValues?: string[];
    systemField?: boolean;
  };
  enumOptions?: Array<{ value: string; label: string }>;
  cascadeConfig?: {
    onDelete?: 'CASCADE' | 'SET NULL' | 'RESTRICT';
    onUpdate?: 'CASCADE' | 'SET NULL' | 'RESTRICT';
  };
}

export interface RDGColumn<T = any> extends Column<T> {
  rdgConfig?: RDGColumnMetadata;
}

// Import types from client entities
import type {
  ${entityImports}
} from './client-entities.js';

`;

  // Import enum options from column configurations
  const enumImports = ['ProjectStatusOptions', 'TaskStatusOptions', 'TaskPriorityOptions', 'UserRoleOptions'];
  
  output += `// Import enum options from column configurations
import {
  ${enumImports.join(',\n  ')}
} from './column-configurations.js';

`;

  // Helper function to find schema for entity
  function findSchemaForEntity(entityName: string): any {
    for (const [key, value] of Object.entries(ClientEntities)) {
      if (key === `${entityName}Schema` && value && typeof value === 'object' && 'options' in value) {
        return value;
      }
    }
    return null;
  }

  // Generate column configurations for each entity
  entityClasses.forEach(entity => {
    const entityName = entity.name;
    const entitySchema = findSchemaForEntity(entityName);
    
    if (!entitySchema) {
      console.warn(`No schema found for entity ${entityName}`);
      return;
    }

    const columns = entitySchema.options.columns || {};
    const relations = entitySchema.options.relations || {};

    output += `export const ${entityName}RDGColumns: RDGColumn<${entityName}>[] = [\n`;

    // Define column order preferences
    const columnOrder = ['id', 'name', 'title', 'email', 'status', 'priority'];
    const processedColumns = new Set<string>();

    // Helper to check if we should skip a column
    const shouldSkipColumn = (propertyName: string, columnDef: any, relations: any) => {
      // Skip system fields that users don't need to see
      if (propertyName === 'clientId') {
        return true;
      }
      
      // Skip foreign key ID fields if there's a corresponding relationship column
      if (propertyName.endsWith('Id') && propertyName !== 'id') {
        const relationName = propertyName.replace('Id', '');
        // Check if there's a corresponding relationship
        if (relations[relationName]) {
          return true;
        }
      }
      
      return false;
    };

    // Helper to generate column
    const generateColumn = (propertyName: string, columnDef: any) => {
      // Skip unwanted columns
      if (shouldSkipColumn(propertyName, columnDef, relations)) {
        return;
      }

      const columnType = columnDef.type;
      const isNullable = columnDef.nullable || false;

      let cellType = 'text';
      let width = 150;
      let editable = true;

      // Determine cell type and default width
      if (propertyName === 'id') {
        cellType = 'uuid';
        editable = false;
      } else if (columnType === 'timestamp' || columnType === 'timestamptz' || columnType === 'date') {
        cellType = 'date';
      } else if (columnType === 'boolean') {
        cellType = 'boolean';
      } else if (columnType === 'int' || columnType === 'integer' || columnType === 'number' || columnType === 'decimal') {
        cellType = 'number';
      } else if (columnType === 'enum') {
        cellType = 'enum';
      } else if (columnType === 'json' || columnType === 'jsonb') {
        cellType = 'json';
      } else {
        cellType = 'text';
      }

      // Get proper widths based on cell type
      width = getDefaultWidth(cellType);
      const minWidth = getMinWidth(cellType);

      // System fields are not editable
      const isSystemField = ['id', 'createdAt', 'updatedAt', 'clientId'].includes(propertyName);
      if (isSystemField) {
        editable = false;
      }

      output += `  {
    key: '${propertyName}',
    name: '${camelToWords(propertyName)}',
    width: ${width},
    minWidth: ${minWidth},
    maxWidth: ${width * 3},
    resizable: true,
    sortable: true,`;

      if (propertyName === 'id') {
        output += `
    frozen: true,`;
      }

      if (!editable) {
        output += `
    editable: false,`;
      } else {
        output += `
    editable: true,`;
      }

      // RDG metadata with enhanced pre-built configuration
      output += `
    rdgConfig: {
      cellType: '${cellType}',`;

      // Add config based on cell type with full editing capabilities
      if (cellType === 'enum' && columnDef.enum) {
        const enumName = `${entityName}${pascalToWords(propertyName).replace(/\s+/g, '')}Options`;
        output += `
      enumOptions: Object.entries(${enumName}).map(([value, label]) => ({ value, label })),`;
        
        output += `
      config: {
        editable: ${editable},
        enumValues: ${enumName},
        searchable: true,
        allowCreate: false,
        placeholder: 'Select ${camelToWords(propertyName).toLowerCase()}...'
      },`;
      } else if (cellType === 'date') {
        const showTime = columnType === 'timestamp' || columnType === 'timestamptz';
        output += `
      config: {
        editable: ${editable},
        format: '${showTime ? 'MMM dd, yyyy HH:mm' : 'MMM dd, yyyy'}',
        showTime: ${showTime}
      },`;
      } else if (cellType === 'text') {
        output += `
      config: {
        editable: ${editable},
        placeholder: 'Enter ${camelToWords(propertyName).toLowerCase()}...',
        maxLength: ${columnDef.length || 500}
      },`;
      } else if (cellType === 'number') {
        output += `
      config: {
        editable: ${editable},
        placeholder: 'Enter ${camelToWords(propertyName).toLowerCase()}...',
        numberMin: 0,
        step: 1
      },`;
      } else if (cellType === 'boolean') {
        output += `
      config: {
        editable: ${editable}
      },`;
      } else if (cellType === 'uuid') {
        output += `
      config: {
        editable: ${editable}
      },`;
      } else {
        output += `
      config: {
        editable: ${editable},
        placeholder: 'Enter ${camelToWords(propertyName).toLowerCase()}...'
      },`;
      }

      // Add business logic for system fields
      if (isSystemField) {
        output += `
      businessLogic: {
        systemField: true,
        auditLog: false
      }`;
      } else if (propertyName.endsWith('Id') && propertyName !== 'id') {
        // This is likely a foreign key
        const targetEntity = pascalToWords(propertyName.replace('Id', ''));
        output += `
      businessLogic: {
        relationship: true,
        requiresValidReference: true,
        targetEntity: '${targetEntity}',
        auditLog: true
      }`;
      }

      output += `
    }
  },\n`;
    };

    // Process columns in preferred order first
    columnOrder.forEach(colName => {
      if (columns[colName]) {
        generateColumn(colName, columns[colName]);
        processedColumns.add(colName);
      }
    });

    // Process remaining columns
    Object.entries(columns).forEach(([propertyName, columnDef]) => {
      if (!processedColumns.has(propertyName)) {
        generateColumn(propertyName, columnDef);
      }
    });

    // Add relation columns with full editing logic
    Object.entries(relations).forEach(([propertyName, relationDef]) => {
      const relation = relationDef as any;
      let relationCellType = 'relationship-single';
      let relationWidth = getDefaultWidth('relation');
      let relationMinWidth = getMinWidth('relation');
      let allowCreate = true;

      // Determine cell type based on relationship type
      if (relation.type === 'many-to-many') {
        relationCellType = 'relationship-multi';
        relationWidth = 280; // Wider for multiple badges (3+ items)
        relationMinWidth = 200; // Wider minimum to fit multiple badges
        allowCreate = false; // Many-to-many typically don't allow creation
      } else if (relation.type === 'one-to-many') {
        relationCellType = 'relationship-collection';
        relationWidth = getDefaultWidth('relationship-collection');
        relationMinWidth = getMinWidth('relationship-collection');
        allowCreate = false; // Collections are typically read-only
      }

      if (relation.type === 'many-to-one' || relation.type === 'many-to-many' || relation.type === 'one-to-many') {
        const targetEntityName = relation.target || 'Unknown';

        // Determine search fields based on target entity
        let searchFields = ['name'];
        let displayField = 'name';
        
        if (targetEntityName === 'User') {
          searchFields = ['name', 'email'];
          displayField = 'name';
        } else if (targetEntityName === 'Task') {
          searchFields = ['title', 'description'];
          displayField = 'title';
        } else if (targetEntityName === 'Project') {
          searchFields = ['name', 'description'];
          displayField = 'name';
        } else if (targetEntityName === 'Comment') {
          searchFields = ['content'];
          displayField = 'content';
        }

        // Make collections read-only
        const isEditable = relation.type !== 'one-to-many';

        // Set max width based on relationship type
        const maxWidth = relation.type === 'many-to-many' ? 500 : relationWidth * 2;

        // For many-to-one relationships, use the foreign key field name instead of relationship name
        let columnKey = propertyName;
        if (relation.type === 'many-to-one') {
          // Convert relationship name to foreign key field name (e.g., 'project' -> 'projectId')
          columnKey = `${propertyName}Id`;
        }

        output += `  {
    key: '${columnKey}',
    name: '${pascalToWords(propertyName)}',
    width: ${relationWidth},
    minWidth: ${relationMinWidth},
    maxWidth: ${maxWidth},
    resizable: true,
    sortable: true,
    editable: ${isEditable},
    rdgConfig: {
      cellType: '${relationCellType}',
      config: {
        editable: ${isEditable},
        relationshipType: '${relation.type}',
        targetEntity: '${targetEntityName}',
        displayField: '${displayField}',
        searchFields: ${JSON.stringify(searchFields)},
        searchable: true,
        allowCreate: ${allowCreate}
      },
      businessLogic: {
        relationship: true,
        requiresValidReference: true,
        targetEntity: '${targetEntityName}',
        auditLog: true,
        requiresPermission: '${entityName.toLowerCase()}:update:${propertyName}'
      }
    }
  },\n`;
      }
    });

    output += `];\n\n`;
  });

  // Add utility functions
  output += `// Utility function to get columns by entity name
export function getRDGColumns(entityName: string): RDGColumn<any>[] {
  const columnsMap: Record<string, RDGColumn<any>[]> = {
`;

  entityClasses.forEach(entity => {
    const entityName = entity.name;
    output += `    ${entityName}: ${entityName}RDGColumns,\n`;
  });

  output += `  };
  
  return columnsMap[entityName] || [];
}

// Export all column configurations
export const RDGColumnConfigurations = {
`;

  entityClasses.forEach(entity => {
    const entityName = entity.name;
    output += `  ${entityName}: ${entityName}RDGColumns,\n`;
  });

  output += `};\n`;

  return output;
}

// Run the generator
generateRDGColumns().catch(console.error);